// This code runs inside the existing app closure. References keep their original storage.
const C04=window.TilesStudyCore;
function studyDefaults(){return {schema:'tiles-evolution-preview',version:'0.4.0',physicalTimeSeconds:0,displayTime:0,history:{...window.TilesStudyCore.historyDefaults},detail:{pan:1,cover:1},roofId:'jiangwutang-study-roof',roofSeed:67191,presentation:{mode:'studio_beauty',rotation:0,exposure:1,key:{enabled:true,intensity:3.2,kelvin:5500},fill:{enabled:true,intensity:1.2,kelvin:7000},rim:{enabled:true,intensity:2.2,kelvin:6500}}};}
function validateStudy(raw){const d=studyDefaults();if(raw===undefined)return d;if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('演化配置无效');for(const k of Object.keys(raw))if(!Object.hasOwn(d,k))throw Error('未知演化字段 '+k);if(raw.schema!==d.schema||raw.version!==d.version)throw Error('演化配置版本不匹配');const num=(v,a,b)=>{if(!Number.isFinite(v)||v<a||v>b)throw Error('演化参数越界');return v;};d.physicalTimeSeconds=num(raw.physicalTimeSeconds,0,86400*90);d.displayTime=num(raw.displayTime,0,1e9);if(typeof raw.roofId!=='string'||raw.roofId.length>120)throw Error('屋面身份无效');d.roofId=raw.roofId;d.roofSeed=num(raw.roofSeed,1,4294967295);if(!Number.isInteger(d.roofSeed))throw Error('屋面种子须为整数');
 for(const k of Object.keys(raw.history||{}))if(!Object.hasOwn(d.history,k))throw Error('未知历史字段 '+k);d.history={...d.history,...raw.history};C04.evolve(C04.tile(),0,d.history);
 for(const k of Object.keys(raw.detail||{}))if(!['pan','cover'].includes(k))throw Error('未知细节母体');for(const k of['pan','cover'])d.detail[k]=num(raw.detail?.[k]??1,0,2);
 const p=raw.presentation;if(!p||typeof p!=='object')throw Error('缺少展示配置');for(const k of Object.keys(p))if(!Object.hasOwn(d.presentation,k))throw Error('未知展示字段 '+k);if(!['studio_beauty','neutral_inspection','diagnostic'].includes(p.mode))throw Error('未知展示模式');d.presentation.mode=p.mode;d.presentation.rotation=num(p.rotation,-180,180);d.presentation.exposure=num(p.exposure,.5,1.5);
 for(const k of['key','fill','rim']){if(!p[k]||typeof p[k].enabled!=='boolean')throw Error('灯光字段无效');for(const n of Object.keys(p[k]))if(!['enabled','intensity','kelvin'].includes(n))throw Error('未知灯光字段');d.presentation[k]={enabled:p[k].enabled,intensity:num(p[k].intensity,0,6),kelvin:num(p[k].kelvin,2500,10000)};}return d;}
function studyActive(){return project.materialPreset==='relief-v04'&&['pan','cover'].includes(project.active);}
function specimen04(id,c,s,entity){const t=C04.tile(id,entity,s.master,c,s);t.parameters.relief=project.study.detail[id];return t;}
function buildGeometry(id,c,s,quality=1,sourceOnly=false){if(!studyActive()||!['pan','cover'].includes(id))return buildLegacyGeometry(id,c,s,quality,sourceOnly);return makeMesh04(id,c,s,'specimen/'+id+'/'+s.master,quality);}
function makeMesh04(id,c,s,entity,quality=1,exposure=1){const t=specimen04(id,c,s,entity),state=C04.evolve(t,project.study.physicalTimeSeconds,project.study.history,exposure),budget=quality===0?[28,36]:quality===3?[48,64]:[112,148],m=C04.mesh(t,{nu:budget[0],nv:budget[1],damage:state.damage});return {...m,coords:m.uv,faces:m.face,deltas:m.relief,profile:id,seeds:{...s},tile:t,state,v04:true,exposure};}
function meshes04(){if(project.layout!=='roof')return(project.layout==='trio'?[0,1,2]:[project.selectedChild]).map((i)=>{const s=childSeeds(cfg().seeds,i),m=makeMesh04(project.active,clone(cfg().controls),s,'specimen/'+project.active+'/'+i);m.child=i;m.offset=[project.layout==='trio'?(i-1)*cfg().controls.width*.014:0,0,0];return m;});
 const out=[],pan=project.profiles.pan.controls,cov=project.profiles.cover.controls,span=pan.width*.0095,step=pan.length*.0063,angle=-.24;
 for(let row=0;row<4;row++)for(let col=0;col<7;col++){const id=col%2?'cover':'pan',j=Math.floor(col/2),c=project.profiles[id].controls,entity=project.study.roofId+'/'+id+'/'+row+'/'+j,bank=project.profiles[id].seeds,s={...bank,master:C04.hash(bank.master+'|'+project.study.roofSeed+'|'+entity)||1};for(const k of Object.keys(SEED_LABELS))s[k]=C04.hash(bank[k]+'|'+entity+'|'+project.study.roofSeed)||1;const x=(col/2-1.5)*span,z=(row-1.5)*step,y=(id==='cover'?pan.curve*.005+cov.curve*.005+.006:0)+row*.009;const m=makeMesh04(id,clone(c),s,entity,3,.72+row*.055+(id==='cover'?.08:0));m.offset=[x,y*Math.cos(angle)-z*Math.sin(angle),y*Math.sin(angle)+z*Math.cos(angle)];m.slope=angle;m.roof=true;m.row=row;m.col=col;out.push(m);}return out;}
class Renderer extends LegacyRenderer{
 constructor(canvas){super(canvas);this.originalCanvas=canvas;this.reliefCanvas=document.createElement('canvas');this.reliefCanvas.className='study-canvas';this.reliefCanvas.tabIndex=0;this.reliefCanvas.setAttribute('aria-label','V0.4 立体瓦面，拖动旋转，滚轮放大');this.reliefCanvas.style.display='none';canvas.parentNode.append(this.reliefCanvas);const prev=this.canvas;this.canvas=this.reliefCanvas;this.installControls();this.canvas=prev;this.studio04=null;this.using04=false;}
 setMeshes(ds,fit){if(ds[0]?.v04){if(!this.studio04)this.studio04=new window.TilesStudyStudio(this.reliefCanvas);this.using04=true;this.originalCanvas.id='gl-legacy';this.reliefCanvas.id='gl';this.originalCanvas.style.display='none';this.reliefCanvas.style.display='block';this.studio04.setMeshes(ds);if(fit)this.reset();else this.draw();}else{this.using04=false;this.originalCanvas.id='gl';this.reliefCanvas.id='gl-v04-hidden';this.reliefCanvas.style.display='none';this.originalCanvas.style.display='block';super.setMeshes(ds,fit);}}
 reset(){if(!this.using04)return super.reset();const r=this.reliefCanvas.getBoundingClientRect(),box=this.studio04.bounds,size=box.getSize(new R.Vector3()),center=box.getCenter(new R.Vector3());this.yaw=-.40;this.pitch=.76;this.target=center.toArray();this.distance=Math.max(size.x/Math.max(.35,r.width/Math.max(1,r.height))*1.8,size.z*1.9,.38);this.draw();}
 draw(){if(!this.using04||!this.studio04)return super.draw();this.studio04.draw(this,project,id=>project.profiles[id].controls,d=>{if(d.roof)return d.seeds;return childSeeds(project.profiles[d.profile].seeds,d.child??project.selectedChild);});document.body.dataset.tilesMotherReady='true';document.body.dataset.version=VERSION;updateStudyStatus();}
}
function studyRebuild(fit=false){if(!studyActive()||!renderer)return legacyRebuild(fit);try{project.study=validateStudy(project.study);const start=performance.now();currentMeshes=meshes04();geometryBuilds++;renderer.setMeshes(currentMeshes,fit);$('loading').classList.add('hidden');$('buildStatus').textContent='V0.4 · '+currentMeshes.reduce((n,m)=>n+m.indices.length/3,0).toLocaleString()+' 三角面 · '+Math.round(performance.now()-start)+' ms';updateMeta();updateStudyStatus();}catch(e){console.error(e);showFatal(e.message);}}
function updateStudyStatus(){if(!$('studyStatus'))return;const active=studyActive();$('studyStatus').textContent=active?'研究候选 · 原始尺度未标定 · 视觉与生产批准待确认':'V0.2 / V0.3 回退观察';$('studioOptions').style.display=active?'block':'none';$('control-glaze').disabled=active;$('palette').disabled=active;if(!active)return;const list=currentMeshes.filter(m=>m.v04),wet=list.length?list.reduce((a,m)=>a+m.state.wetness,0)/list.length:0,depth=list.length?Math.max(...list.map(m=>m.metrics.topPeakToValley)):0;
 $('specimenCaption').textContent='真实网格起伏 · 孔沿与浅剥落 · 独立手工成型场';$('familyCode').textContent='TILES MOTHER / RELIEF 0.4.0';$('specimenTitle').textContent=project.layout==='roof'?'同一历史 · 28 块瓦':PROFILE_DEFS[project.active].name;$('specimenMeasure').textContent='候选起伏范围 '+(depth*1000).toFixed(2)+' mm · '+(project.study.physicalTimeSeconds/86400).toFixed(1)+' 示意日 · 平均含水 '+Math.round(wet*100)+'%';$('timeValue').textContent=(project.study.physicalTimeSeconds/86400).toFixed(1);$('roofTime').value=project.study.physicalTimeSeconds/86400;$('mode04').value=project.study.presentation.mode;$('relief04').value=project.study.detail[project.active];
 const labels={normal:'表面法线：方向映射 RGB',cavity:'浅凹事件：浅色低 / 蓝色高',roughness:'粗糙度：黑色光滑 / 白色粗糙',weather:'累积湿暴露：浅色低 / 蓝色高',relief:'真实表面偏移：蓝色下凹 / 赭色凸起',wetness:'含水：米白干 / 蓝色湿',damage:'累计不可逆损伤：浅色低 / 红色高',wire:'实际三角网格',source:'纯色几何，保留所有真实起伏'};$('diagnosticLegend').textContent=labels[project.channel]||'左键旋转 · 滚轮特写 · 光照独立于瓦片历史';
}
function setupStudyUI(){
 const sec=document.createElement('section');sec.className='section study-panel';sec.innerHTML=`<div class="eyebrow">RELIEF / HISTORY / LIGHT</div><h2 class="section-title">立体瓦面与屋面历史</h2><div id="studyStatus" class="explain"></div><div id="studioOptions"><label class="note-label">表面起伏 <small>候选强度，0 为关闭</small></label><input id="relief04" aria-label="真实起伏强度" type="range" min="0" max="2" step="0.05" value="1"><label class="note-label">统一时间 <output id="timeValue">0</output> 示意日</label><input id="roofTime" aria-label="屋面统一时间" type="range" min="0" max="90" step="0.25" value="0"><div class="row wrap"><button id="play04" class="small">播放时间</button><button id="roof04" class="small">屋面样方</button><button id="single04" class="small">单块特写</button></div><label class="note-label">共享环境历史</label><select id="history04"><option value="wet-dry">雨淋与干燥循环</option><option value="rain">持续雨淋</option><option value="dry">始终干燥</option></select><p class="explain">所有瓦片共享过程时间，各自保留身份、暴露和损伤。时间与速率均为未标定示意，不对应实物年份。</p><label class="note-label">观察灯光</label><select id="mode04"><option value="studio_beauty">工作室展示</option><option value="neutral_inspection">中性检查</option><option value="diagnostic">斜光诊断</option></select><details id="lights04"><summary>主光 / 辅光 / 轮廓光</summary><div id="lightControls04"></div><label class="note-label">整组旋转</label><input id="lightRotation04" aria-label="灯光旋转" type="range" min="-180" max="180" step="1" value="0"><p class="explain">强度为 Three.js 相对预览单位。色温为近似 RGB 转换。中性与诊断模式锁定灯光及曝光。</p></details><button id="exportState04" class="small">导出轻量状态</button><p id="diagnosticLegend" class="explain"></p></div>`;
 document.querySelector('.control-rail').insertBefore(sec,document.querySelector('.control-rail').children[1]);const o=document.createElement('option');o.value='relief-v04';o.textContent='立体瓦面 V0.4';$('materialPreset').prepend(o);$('materialPreset').value=project.materialPreset;
 for(const [key,label]of[['relief','真实起伏'],['wetness','含水诊断'],['damage','损伤诊断'],['wire','三角网格']]){const o=document.createElement('option');o.value=key;o.textContent=label;$('channel').append(o);}
 $('relief04').oninput=e=>{project.study.detail[project.active]=Number(e.target.value);scheduleBuild();saveSoon();};$('roofTime').oninput=e=>setTime04(Number(e.target.value)*86400);$('history04').onchange=e=>{project.study.history.preset=e.target.value;rebuild();saveSoon();};$('mode04').onchange=e=>setPresentation04({mode:e.target.value});$('lightRotation04').oninput=e=>setPresentation04({rotation:Number(e.target.value)});
 for(const [key,label]of[['key','主光'],['fill','辅光'],['rim','轮廓光']]){const el=document.createElement('div');el.innerHTML=`<label class="note-label"><input type="checkbox" id="light-${key}-on" checked> ${label}</label><input aria-label="${label}强度" id="light-${key}-power" type="range" min="0" max="6" step=".1"><label class="explain">色温 Kelvin</label><input aria-label="${label}色温" id="light-${key}-kelvin" type="range" min="2500" max="10000" step="100">`;$('lightControls04').append(el);$('light-'+key+'-power').value=project.study.presentation[key].intensity;$('light-'+key+'-kelvin').value=project.study.presentation[key].kelvin;for(const [suffix,field]of[['on','enabled'],['power','intensity'],['kelvin','kelvin']])$('light-'+key+'-'+suffix).oninput=e=>setPresentation04({[key]:{...project.study.presentation[key],[field]:suffix==='on'?e.target.checked:Number(e.target.value)}});}
 $('roof04').onclick=()=>{if(!studyActive()){project.active='pan';project.materialPreset='relief-v04';}project.layout='roof';syncUI();rebuild(true);saveSoon();};$('single04').onclick=()=>{project.layout='single';syncUI();rebuild(true);saveSoon();};let timer=0;
 $('play04').onclick=()=>{if(timer){clearInterval(timer);timer=0;$('play04').textContent='播放时间';return;}$('play04').textContent='暂停';timer=setInterval(()=>{project.study.displayTime+=.5;const time=Math.min(90*86400,project.study.physicalTimeSeconds+86400*.5);setTime04(time);if(time>=90*86400){clearInterval(timer);timer=0;$('play04').textContent='播放时间';}},500);};
 $('exportState04').onclick=()=>{const payload={schema:'tiles-mother-lightweight-state',version:VERSION,project:clone(project),geometryHashes:currentMeshes.map(m=>bufferHash(m.positions)),history:currentMeshes.filter(m=>m.v04).map(m=>m.state),presentation:renderer?.studio04?.last||null,visualApproved:false,productionApproved:false};download(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),'Tiles_Mother_V04_State.json');};
 $('materialPreset').onchange=e=>{project.materialPreset=e.target.value;if(project.materialPreset!=='relief-v04'&&project.layout==='roof')project.layout='single';syncUI();rebuild(true);saveSoon();};
 updateStudyStatus();
}
function setTime04(seconds){if(!Number.isFinite(seconds)||seconds<0||seconds>90*86400)throw Error('示意时间越界');project.study.physicalTimeSeconds=seconds;scheduleBuild();saveSoon();updateStudyStatus();}
function setPresentation04(patch){const next=clone(project.study);Object.assign(next.presentation,patch);project.study=validateStudy(next);renderer?.draw();saveSoon();}
function attachStudyAPI(){window.TilesMother.study={version:'0.4.0',setTime:setTime04,setPresentation:setPresentation04,setRelief:v=>{if(!Number.isFinite(v)||v<0||v>2)throw Error('起伏越界');project.study.detail[project.active]=v;rebuild();saveSoon();},setHistory:h=>{const n=clone(project.study);n.history={...n.history,...h};project.study=validateStudy(n);rebuild();saveSoon();},roof:()=>{$('roof04').click();},metrics:()=>currentMeshes.filter(m=>m.v04).map(m=>({id:m.tile.id,profile:m.profile,metrics:m.metrics,state:m.state,hash:bufferHash(m.positions),seedLineage:m.tile.seeds})),presentation:()=>renderer?.studio04?.last||null,sourceFingerprint:()=>C04.fingerprint([JSON.stringify(project.profiles),JSON.stringify(project.study.history),project.study.physicalTimeSeconds,JSON.stringify(project.study.detail),project.study.roofSeed]),validate:validateStudy};}

function rebuild(fit=false){return studyRebuild(fit);}
