/* Study pane in Tiles Mother. Original reference desk stays unchanged. */
(()=>{'use strict';const C=window.TilesStudyCore,T=window.TMThree,$=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
const S={version:C.VERSION,shape:'pan',trio:false,seed:32017,relief:1,pores:1,forming:1,day:0,weather:'wet-dry',rain:1,mode:'studio',channel:'final',azimuth:-20,elevation:35,key:3.2,fill:.7,rim:1.8};
let renderer,scene,camera,orbit,group,lightRig,key,fill,rim,ambient,floor,manifest={},entries=[],timer,builds=0,ready=false,priorRelief=1;
function validatePatch(p){const ranges={seed:[1,4294967295],relief:[0,2],pores:[0,2],forming:[0,2],day:[0,120],rain:[0,2],key:[0,6],fill:[0,3],rim:[0,5],azimuth:[-180,180],elevation:[10,85]};const enums={shape:['pan','cover','roof'],mode:['studio','neutral','diagnostic'],channel:['final','clay','wire','normal','depth','albedo','cavity','wetness','roughness'],weather:['wet-dry','rain','dry']};for(const [k,v] of Object.entries(p)){if(ranges[k]){if(!Number.isFinite(v)||v<ranges[k][0]||v>ranges[k][1]||(k==='seed'&&!Number.isInteger(v)))throw Error('invalid '+k);}else if(enums[k]){if(!enums[k].includes(v))throw Error('invalid '+k);}else if(k==='trio'){if(typeof v!=='boolean')throw Error('invalid trio');}else throw Error('unknown '+k);}return p;}
const geometryParams=()=>({relief:S.relief,pores:S.pores,forming:S.forming});
function receipt(){return {version:C.VERSION,source:'yunnan-jiangwutang-tiles-001',referenceOrigin:'Codex source analysis; raw FBX not present in this viewer',policyVersion:'1.0.0',policyRuntimeAdoptionVerified:false,config:clone(S),entityCount:entries.length,entities:entries.map(e=>({id:e.tile.id,profile:e.tile.profile,seeds:clone(e.tile.seeds),metrics:e.data.metrics,history:e.state,geometryHash:C.fingerprint(e.data.positions)})),presentation:{mode:S.mode,colorPipeline:'Three r180 linear working / sRGB output / neutral NoToneMapping / studio ACESFilm',lightIntensityUnit:'relative',nativePixels:renderer?[renderer.domElement.width,renderer.domElement.height]:null,displayTimeSeconds:0},build:manifest,visualApproved:false,productionApproved:false,distillationComplete:false};}
const save=()=>{try{localStorage.setItem('tiles-mother-surface-study-v04',JSON.stringify(S));}catch{}};
function configureLight(){const neutral=S.mode==='neutral',diagnostic=S.mode==='diagnostic';const angle=(neutral?-35:diagnostic?-65:S.azimuth)*Math.PI/180,elev=(neutral?45:diagnostic?14:S.elevation)*Math.PI/180;lightRig.rotation.y=angle;key.position.set(-Math.cos(elev)*1.3,Math.sin(elev)*1.3,.5);fill.position.set(1,.4,.5);rim.position.set(.6,.65,-1);key.intensity=neutral?2.0:diagnostic?2.8:S.key;fill.intensity=neutral?.6:diagnostic?.15:S.fill;rim.intensity=neutral?0:diagnostic?.4:S.rim;ambient.intensity=neutral?.8:diagnostic?.45:.65;
 key.color.setRGB(1,neutral?1:.91,neutral?1:.80);fill.color.setRGB(neutral?1:.81,neutral?1:.90,1);rim.color.setRGB(.89,.94,1);scene.background.set(neutral?'#b5b5b5':'#262b31');floor.material.color.set(neutral?'#a8a8a8':'#343b44');renderer.toneMapping=neutral?T.NoToneMapping:T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;$('lights').style.opacity=neutral||diagnostic?'.4':'1';$('lights').querySelectorAll('input').forEach(x=>x.disabled=neutral||diagnostic);}
const microGLSL=`varying vec3 tmPosition;varying float tmRough;varying float tmCavity;
float tmhash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}
float tmnoise(vec3 p){vec3 a=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(tmhash(a),tmhash(a+vec3(1,0,0)),f.x),mix(tmhash(a+vec3(0,1,0)),tmhash(a+vec3(1,1,0)),f.x),f.y),mix(mix(tmhash(a+vec3(0,0,1)),tmhash(a+vec3(1,0,1)),f.x),mix(tmhash(a+vec3(0,1,1)),tmhash(a+vec3(1,1,1)),f.x),f.y),f.z);}`;
function material(tile){if(S.channel==='normal')return new T.MeshNormalMaterial({side:T.DoubleSide});if(S.channel==='depth')return new T.MeshDepthMaterial({side:T.DoubleSide});if(S.channel==='wire')return new T.MeshBasicMaterial({color:0xc1b49b,wireframe:true});if(['albedo','cavity','wetness','roughness'].includes(S.channel))return new T.MeshBasicMaterial({vertexColors:true,side:T.DoubleSide});
 const m=new T.MeshStandardMaterial({vertexColors:S.channel!=='clay',color:S.channel==='clay'?0xa7a29a:0xffffff,roughness:.85,metalness:0,side:T.DoubleSide});m.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nattribute float tmRoughness;attribute float tmCavityField;varying vec3 tmPosition;varying float tmRough;varying float tmCavity;').replace('#include <begin_vertex>','#include <begin_vertex>\ntmPosition=position;tmRough=tmRoughness;tmCavity=tmCavityField;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\n'+microGLSL).replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nroughnessFactor=tmRough;');if(S.channel==='final'){shader.fragmentShader=shader.fragmentShader.replace('#include <normal_fragment_maps>',`#include <normal_fragment_maps>
vec3 tmP=tmPosition*780.+vec3(${(tile.seeds.micro%17011).toFixed(1)},0.,0.);float tmAA=1.-smoothstep(.30,1.6,length(fwidth(tmP)));float tmB=(tmnoise(tmP)-.5)*.000035*tmAA;vec3 tmDX=dFdx(-vViewPosition),tmDY=dFdy(-vViewPosition);vec3 tmR1=cross(tmDY,normal),tmR2=cross(normal,tmDX);float tmD=dot(tmDX,tmR1);if(abs(tmD)>1e-12)normal=normalize(abs(tmD)*normal-sign(tmD)*(dFdx(tmB)*tmR1+dFdy(tmB)*tmR2));`);}shader.fragmentShader=shader.fragmentShader.replace('#include <aomap_fragment>','#include <aomap_fragment>\nreflectedLight.indirectDiffuse*=1.-tmCavity*.20;');};m.customProgramCacheKey=()=>S.channel+'-tm04-'+tile.seeds.micro;return m;}
function colorGeometry(e){const d=e.data,colors=new Float32Array(d.positions.length),rough=new Float32Array(d.positions.length/3);for(let i=0;i<rough.length;i++){const u=d.uv[i*2]*2-1,v=d.uv[i*2+1]*2-1,ap=C.appearance(u,v,e.tile,e.state,{flake:d.flakes[i],cavity:d.cavities[i]},d.face[i]>0);let col=ap.linearColor;if(S.channel==='cavity')col=[ap.cavity*.95+.025,.07+ap.cavity*.36,.08];if(S.channel==='wetness')col=[.03,.08+ap.wetness*.32,.1+ap.wetness*.8];if(S.channel==='roughness')col=[ap.roughness,ap.roughness,ap.roughness];colors.set(col,i*3);rough[i]=ap.roughness;}e.geometry.setAttribute('color',new T.BufferAttribute(colors,3));e.geometry.setAttribute('tmRoughness',new T.BufferAttribute(rough,1));e.geometry.setAttribute('tmCavityField',new T.BufferAttribute(d.cavities,1));}
function specimens(){if(S.shape==='roof'){const out=[];for(let row=0;row<3;row++)for(let col=0;col<3;col++){out.push({p:'pan',id:`roof/pan/${row}/${col}`,pos:[(col-1)*.198,row*.013,-row*.218+.218],exposure:.68+row*.12});if(col<2)out.push({p:'cover',id:`roof/cover/${row}/${col}`,pos:[(col-.5)*.198,.061+row*.013,-row*.218+.218],exposure:.75+row*.12});}return out;}return Array.from({length:S.trio?3:1},(_,i)=>({p:S.shape,id:`single/${S.shape}/${i}`,pos:[S.trio?(i-1)*.27:0,0,0],exposure:1}));}
function rebuild(fit=false){$('loading').style.display='block';try{for(const e of entries){group.remove(e.mesh);e.geometry.dispose();e.mesh.material.dispose();}entries=[];const budget=S.shape==='roof'?{nu:56,nv:76}:{nu:112,nv:148};for(const item of specimens()){const tile=C.tile(item.p,item.id,S.seed);tile.parameters=geometryParams();const state=C.evolve(tile,S.day*86400,{preset:S.weather,rain:S.rain},item.exposure);const data=C.mesh(tile,{...budget,damage:state.damage}),g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(data.positions,3));g.setAttribute('uv',new T.BufferAttribute(data.uv,2));g.setIndex(new T.BufferAttribute(data.indices,1));g.computeVertexNormals();const e={tile,state,data,geometry:g};colorGeometry(e);const obj=new T.Mesh(g,material(tile));obj.position.fromArray(item.pos);obj.castShadow=true;obj.receiveShadow=true;e.mesh=obj;group.add(obj);entries.push(e);}group.rotation.x=S.shape==='roof'?.13:0;builds++;const bb=new T.Box3().setFromObject(group);floor.position.y=bb.min.y-.012;if(fit)fitCamera();configureLight();draw();ready=true;$('status').textContent=`${entries.length} 个瓦件 · ${entries.reduce((s,e)=>s+e.data.indices.length/3,0).toLocaleString()} 三角面 · 同一历史 ${S.day} 示意天`;$('identity').textContent=`V0.4.0 · seed ${S.seed} · ${manifest.sourceCommit?.slice(0,12)||'local candidate'} · ${S.mode} · 人工/生产批准 false`;$('legend').textContent=({cavity:'孔窝字段：橙亮为浅坑影响较强。几何和网格可交叉检查。',wetness:'含水状态：蓝亮为含水较多；未标定示意。',roughness:'粗糙度：亮为更粗糙。候选值，非测量值。',depth:'相机深度：近亮远暗；用于观察曲率和高低关系。',normal:'实际几何法线：RGB 表示朝向；此通道不叠加微凹凸。'})[S.channel]||'左键旋转 · 滚轮缩放 · 右键平移 · 双击归位';save();}catch(err){ready=false;$('fatal').textContent=err.message;console.error(err);}finally{$('loading').style.display='none';}}
function fitCamera(){const b=new T.Box3().setFromObject(group),c=b.getCenter(new T.Vector3()),size=b.getSize(new T.Vector3());const dist=Math.max(size.x/camera.aspect,size.z,size.y)*1.65;orbit.target.copy(c);camera.position.copy(c).add(new T.Vector3(-dist*.50,dist*.79,dist*.95));camera.near=.002;camera.far=12;camera.updateProjectionMatrix();orbit.update();}
function draw(){if(renderer){renderer.render(scene,camera);}}
function queue(fit=false){clearTimeout(timer);timer=setTimeout(()=>rebuild(fit),80);}
function bind(){document.querySelectorAll('[data-shape]').forEach(b=>b.onclick=()=>{S.shape=b.dataset.shape;document.querySelectorAll('[data-shape]').forEach(x=>x.classList.toggle('active',x===b));queue(true);});for(const k of ['relief','pores','forming','day','rain'])$(k).oninput=e=>{S[k]=Number(e.target.value);const o=$(k+'Value');if(o)o.textContent=k==='day'?S[k]+' 天':S[k].toFixed(2);queue();};$('weather').onchange=e=>{S.weather=e.target.value;queue();};$('seed').onchange=e=>{const v=Number(e.target.value);if(!Number.isInteger(v)||v<1||v>4294967295){e.target.value=S.seed;return;}S.seed=v;queue();};$('next').onclick=()=>{S.seed=C.hash(S.seed+'|next')||1;$('seed').value=S.seed;queue();};$('trio').onclick=()=>{S.trio=!S.trio;$('trio').classList.toggle('active',S.trio);queue(true);};$('mode').onchange=e=>{S.mode=e.target.value;if(S.mode==='neutral')fitCamera();configureLight();draw();save();};$('channel').onchange=e=>{S.channel=e.target.value;queue();};for(const k of ['key','fill','rim','azimuth','elevation'])$(k).oninput=e=>{S[k]=Number(e.target.value);configureLight();draw();save();};$('fit').onclick=()=>{fitCamera();draw();};$('closeup').onclick=()=>{camera.position.sub(orbit.target).multiplyScalar(.57).add(orbit.target);orbit.update();draw();};$('canvas').ondblclick=()=>{fitCamera();draw();};$('reliefCompare').onclick=()=>{if(S.relief>0){priorRelief=S.relief;S.relief=0;}else S.relief=priorRelief;$('relief').value=S.relief;$('reliefValue').textContent=S.relief.toFixed(2);queue();};$('capture').onclick=()=>{draw();renderer.domElement.toBlob(b=>download(b,`TilesMother-v04-${S.shape}-${S.mode}-${S.channel}.png`));};$('save').onclick=()=>download(new Blob([JSON.stringify(receipt(),null,2)],{type:'application/json'}),'TilesMother-v04-effective.json');}
function download(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}
async function init(){try{manifest=await fetch('build-manifest.json').then(r=>{if(!r.ok)throw Error('missing manifest');return r.json();});if(manifest.version!==C.VERSION)throw Error('build version mismatch');renderer=new T.WebGLRenderer({canvas:$('canvas'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;scene=new T.Scene();scene.background=new T.Color('#262b31');camera=new T.PerspectiveCamera(38,1,.002,12);orbit=new T.OrbitControls(camera,$('canvas'));orbit.enableDamping=false;orbit.minDistance=.08;orbit.maxDistance=4;orbit.addEventListener('change',draw);group=new T.Group();scene.add(group);lightRig=new T.Group();scene.add(lightRig);key=new T.DirectionalLight(0xffffff,3.2);fill=new T.DirectionalLight(0xffffff,.7);rim=new T.DirectionalLight(0xffffff,1.8);lightRig.add(key,fill,rim);key.castShadow=true;key.shadow.mapSize.set(1536,1536);Object.assign(key.shadow.camera,{left:-.8,right:.8,top:.8,bottom:-.8,near:.1,far:4});key.shadow.bias=-.000025;key.shadow.normalBias=.00045;ambient=new T.HemisphereLight(0xe4ecf6,0x675e53,.65);scene.add(ambient);floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:0x343b44,roughness:.96}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const resize=()=>{const r=$('stage').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();draw();};new ResizeObserver(resize).observe($('stage'));resize();bind();rebuild(true);window.TilesStudy={version:C.VERSION,receipt,get ready(){return ready;},set(patch){Object.assign(S,validatePatch(patch));rebuild(patch.shape!==undefined||patch.trio!==undefined);},geometryHashes:()=>entries.map(e=>C.fingerprint(e.data.positions)),draw,fit:fitCamera,builds:()=>builds};document.body.dataset.studyReady='true';}catch(e){$('fatal').textContent=e.message;$('loading').textContent='候选未能启动：'+e.message;console.error(e);}}
init();})();
