const fs=require('fs'),vm=require('vm'),path=require('path');const H=__dirname;
const h=fs.readFileSync(H+'/START_HERE.html','utf8');const code=h.match(/<script>([\s\S]*?)<\/script>/)[1];const C={console};vm.createContext(C);vm.runInContext(code.slice(0,code.indexOf('const VERT='))+';this.A={ceramic,timber,M,model,tileModel,SEATS,V,smooth,clamp};',C);const A=C.A,S=A.SEATS;
const smooth=A.smooth,fract=x=>x-Math.floor(x),handHash=x=>fract(Math.sin(x*12.9898+78.233)*43758.5453123);
function hand(p,meta,sid){if(meta[1]<.5)return[0,0,0];let halfW=meta[1]>1.5?.0575:.121,len=meta[1]>1.5?.222:.238,u=A.clamp(p[0]/halfW,-1,1),t=A.clamp(p[2]/len+.5),side=(1-u*u)**2,end=Math.sin(Math.PI*t)**2,a=handHash(sid*1.113)-.5,b=handHash(sid*2.173+3.1)-.5,c=handHash(sid*4.317+1.7)-.5,d=handHash(sid*7.919+5.2)-.5;return[Math.abs(u)**12*(a*.00034+b*.00018*Math.sin(t*7.1+d*3))*Math.sign(u),side*end*(a*.0028+b*.0014*Math.sin(2.3*u+1.7*t+c*4)+c*.0009*(2*t-1)+d*.0007*u),Math.abs(2*t-1)**12*(c*.00055+d*.00028*Math.sin(u*5.3+a*4))]}
function micro(p,m,seed,strength,scale){if(!strength||m[1]<.5)return[0,0,0];let q=[p[0]+(fract(Math.sin(seed*12.9898+78.233)*43758.5453)-.5)*.11,p[2]+.4,p[1]+.27],r=Math.hypot(...q),density=24*scale,xi=[Math.log2(r)-2,-q[2]/r,Math.atan2(q[0],q[1])].map(x=>x*density),span=.006*density/Math.max(Math.hypot(q[0],q[1]),.2),value=0;for(let j=0,s=1;j<17;j++,s*=2){let c=xi.map(x=>Math.cos(x*s));value+=(1-smooth(.8,2.4,span*s))*(Math.cos(c[2]*c[0]+c[1]*c[1]+c[1]*c[0])-.6556965)/s;}value=A.clamp(value,-1,1);let len=m[1]>1.5?.222:.238,u=m[3],t=A.clamp(p[2]/len+.5),z=m[2],top=1-smooth(0,.5,z),side=1-smooth(.70,.90,Math.abs(u)),lap=smooth(.12,.25,t)*(1-smooth(.72,.85,t)),f=(.5+.5*value)*strength;return[-Math.sign(u)*.00012*f*16*z*z*(1-z)**2*smooth(.88,1,Math.abs(u))*lap,-.00035*f*top*side*lap,.00020*f*top*side*(1-smooth(.015,.08,t))]}
const source=fs.readFileSync(path.join(H,'../clean-02/qa/contact.cjs'),'utf8');vm.runInNewContext(source.slice(source.indexOf('function triangles('),source.indexOf('if(process.env.CONTACT_LIB)'))+';this.gap=gap',{A,...C});const G={A};vm.createContext(G);vm.runInContext(source.slice(source.indexOf('function triangles('),source.indexOf('if(process.env.CONTACT_LIB)'))+';this.gap=gap',G);
const results=[],checks=[];let maxOffset=0,bottomMax=0,flips=0;
function mesh(kind,sid,strength,scale){const g=A.ceramic(kind),original=Array.from(g.p);for(let i=0;i<g.p.length/3;i++){const p=original.slice(i*3,i*3+3),m=Array.from(g.meta.slice(i*4,i*4+4)),o=micro(p,m,sid,strength,scale),b=hand(p,m,sid);maxOffset=Math.max(maxOffset,Math.hypot(...o));if(m[2]===1)bottomMax=Math.max(bottomMax,Math.hypot(...o));g.p.set(p.map((v,k)=>v+o[k]+b[k]),i*3);}return g;}
for(const sid of [3,51,99])for(const scale of [.5,1,3]){
 let base={pan:mesh('pan',sid,0,scale),cover:mesh('cover',sid,0,scale)},deformed={pan:mesh('pan',sid,3,scale)};
 // Both load-bearing contacts are unchanged: bottom q=1 and upper side rim |u|>=.9 q=0.
 for(const kind of ['pan','cover']){let raw=A.ceramic(kind);for(let i=0;i<raw.p.length/3;i++){let p=Array.from(raw.p.slice(i*3,i*3+3)),m=Array.from(raw.meta.slice(i*4,i*4+4));if(m[2]===1||(m[2]===0&&Math.abs(m[3])>=.9)){if(Math.hypot(...micro(p,m,sid,3,scale))>1e-12)throw Error('contact rim moved');}}}
}
// Exact projected triangle intersection check for representative rigid assemblies.
for(const strength of [0,3]){
 const pan=mesh('pan',51,strength,.5),cover=mesh('cover',51,strength,.5);
 for(const kind of ['pan','cover']){const m=kind==='pan'?pan:cover,y=kind==='pan'?S.panY:S.coverY;results.push({...G.gap(kind+' lap',m,A.tileModel(kind,0,y,0),m,A.tileModel(kind,0,y,S.step)),strength});}
 for(const side of [-1,1])results.push({...G.gap('cover pan '+side,pan,A.tileModel('pan',side*S.spacing*.5,S.panY,0),cover,A.tileModel('cover',0,S.coverY,S.coverPhase)),strength});
 for(const side of [-1,1])results.push({...G.gap('rafter pan '+side,A.timber(),A.model(side*S.spacing*.5,0,0,0,0,[S.rafterRadius,S.rafterRadius,4.02]),pan,A.tileModel('pan',0,S.panY,0)),strength});
}
const report={scope:'CPU double-precision mirror of shader displacement; exact projected triangle intersections on representative seed 51, scale .5. Not GPU verification or exhaustive all-instance contact proof.',maxOffsetMm:maxOffset*1000,bottomMaxMm:bottomMax*1000,contactRimsExact:true,results,allRepresentativeContactsPassed:results.every(x=>x.pass),visualApproved:false,productionApproved:false};fs.writeFileSync(H+'/GEOMETRY_QA.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
