import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {register} from 'node:module';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {chainCheck,axisCheck,envelopeCheck,drainageEvidence,releaseDecision,AUDIT_VERSION} from './audit-core.mjs';
const app=path.resolve(process.argv[2]||'.'),out=path.resolve(process.argv[3]||new URL('./data',import.meta.url).pathname);fs.mkdirSync(out,{recursive:true});
const sha=f=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');const read=f=>JSON.parse(fs.readFileSync(path.join(app,f),'utf8'));
const generator='threejs/YunnanCourtyardProduction.js',expected='10d083edb5b41bd24e3d9f58de9e4ae2f0d2c6fa2ccc9e8606dfb4ce832f5677';assert.equal(sha(path.join(app,generator)),expected,'legacy generator identity changed: stop');
const cp='data/cases/yunnan_three_bay_front_gallery_two_storey_v5_3_0.json',ep='data/evidence/yunnan_three_bay_front_gallery_sources_v5_3_0.json';
const c=read(cp),e=read(ep);assert.equal(sha(path.join(app,cp)),'a43782f7914067c6f04cfa1411daf5cc1cead977d8a46e352f91fd9085dbaff7');
register('./three-loader.mjs',import.meta.url,{data:{threeUrl:pathToFileURL(path.join(app,'vendor/three/three.module.js')).href}});
const THREE=await import('three');const {createYunnanCourtyardPrototype}=await import(pathToFileURL(path.join(app,generator)).href);
function getGeometry(){const root=createYunnanCourtyardPrototype({seed:401});root.updateMatrixWorld(true);let wall,roof;root.traverse(o=>{if(o.userData.componentId==='WALL-NORTH-GABLE')wall=o;if(o.userData.isRoofUnit&&o.userData.roofUnitId==='mainHouseDoublePitch')roof=o;});assert(wall&&roof);const vector=new THREE.Vector3(),points=[],triangles=[];
 const a=wall.geometry.attributes.position;for(let i=0;i<a.count;i++)points.push(vector.fromBufferAttribute(a,i).applyMatrix4(wall.matrixWorld).toArray());
 roof.traverse(o=>{if(!o.isMesh||o.userData.roofLayerId!=='roofUnderlay')return;assert(!o.isInstancedMesh,'explicit instance expansion required');const p=o.geometry.attributes.position,index=o.geometry.index;for(let i=0;i<(index?index.count:p.count);i+=3){triangles.push([0,1,2].map(j=>vector.fromBufferAttribute(p,index?index.getX(i+j):i+j).applyMatrix4(o.matrixWorld).toArray()));}});
 return {points,triangles,wallIndices:Array.from(wall.geometry.index.array),wallId:wall.userData.componentId,roofId:roof.userData.roofUnitId,legacyCaseId:root.userData.caseId,roofDeclaredRidgeM:roof.userData.ridgeElevationM,roofActualMaxM:new THREE.Box3().setFromObject(roof).max.y,drainageDeclared:roof.userData.drainageContinuous};}
const geom=getGeometry(),old=envelopeCheck(geom.points,geom.triangles);assert.equal(old.status,'fail');
const checks=[{id:'WIDTH',label:'面阔尺寸链',...chainCheck(c.plan.facadeDimensionChain,c.plan.overallWidth)},{id:'DEPTH',label:'进深尺寸链',...chainCheck(c.plan.depthDimensionChain,c.plan.overallDepth)},{id:'AXES',label:'三间与四条构架轴',...axisCheck(c.plan.bayAxesX,c.plan.facadeDimensionChain.slice(1,-1))}];
const sources=e.sources.slice(0,4).map(s=>{const p=path.join(app,s.path);return {...s,present:fs.existsSync(p),hashMatched:fs.existsSync(p)?sha(p)===s.sha256:false};});
checks.push({id:'RAW_SOURCES',label:'四份原图逐项回核',status:sources.every(s=>s.hashMatched)?'pass':'unknown',reason:'旧记录的可用声明与本轮原件核验分开。'}, {id:'GALLERY_BASIS',label:'前廊轴距与净深口径',status:'unknown',reason:'原记录1.87同时为A到B轴距和galleryClearDepth；柱径及测量端点缺失，不自动改值。'}, {id:'ROOF_PROFILE',label:'屋架及屋面控制剖面',status:'unknown',reason:'标高存在；脊线平面位置、坡线与节点原图未复核，不由中点猜出屋顶。'}, {id:'HISTORY',label:'原建身份与1940年代状态',status:'unknown',reason:'原记录为地域未定、现状改造阶段；客房及卫生间不回写成历史原状。'});
const tests=[];function test(name,fn){try{fn();tests.push({name,passed:true});}catch(err){tests.push({name,passed:false,error:err.message});}}
const roof=[[[0,3,0],[2,3,0],[0,3,2]],[[2,3,0],[2,3,2],[0,3,2]]];
test('dimension_chain_pass',()=>assert.equal(chainCheck([.565,3.2,4,3.2,.565],11.53).status,'pass'));
test('dimension_fault_detected',()=>assert.equal(chainCheck([.565,3.2,4,3.3,.565],11.53).status,'fail'));
test('infinity_rejected',()=>assert.throws(()=>chainCheck([Infinity],1)));
test('string_number_rejected',()=>assert.throws(()=>chainCheck(['1'],1)));
test('zero_length_rejected',()=>assert.throws(()=>chainCheck([0],1)));
test('axis_match',()=>assert.equal(axisCheck([0,3,7],[3,4]).status,'pass'));
test('axis_displacement_detected',()=>assert.equal(axisCheck([0,3.1,7],[3,4]).status,'fail'));
test('duplicate_axis_detected',()=>assert.equal(axisCheck([0,0,7],[3,4]).status,'fail'));
test('axis_count_rejected',()=>assert.throws(()=>axisCheck([0,3],[3,4])));
test('wall_below_roof',()=>assert.equal(envelopeCheck([[.5,2.9,.5]],roof).status,'pass'));
test('wall_above_roof_detected',()=>assert.equal(envelopeCheck([[.5,3.3,.5]],roof).status,'fail'));
test('uncovered_point_is_unknown',()=>assert.equal(envelopeCheck([[3,2,3]],roof).status,'unknown'));
test('missing_roof_is_unknown',()=>assert.equal(envelopeCheck([[.5,2,.5]],[]).status,'unknown'));
test('nonfinite_geometry_rejected',()=>assert.throws(()=>envelopeCheck([[0,NaN,0]],roof)));
test('units_mismatch_blocked',()=>assert.throws(()=>envelopeCheck([[0,0,0]],roof,{unit:'cm'})));
test('parapet_needs_separate_rule',()=>assert.throws(()=>envelopeCheck([[0,0,0]],roof,{termination:'parapet'})));
test('source_boolean_cannot_prove_drainage',()=>assert.equal(drainageEvidence(true,null).status,'unknown'));
test('unknown_cannot_be_approved',()=>assert.equal(releaseDecision([{status:'unknown'}]).technicalEligible,false));
test('empty_suite_rejected',()=>assert.throws(()=>releaseDecision([])));
test('automated_pass_cannot_grant_visual',()=>assert.equal(releaseDecision([{status:'pass'}],{primarySourcesVerified:true,historicalIdentityVerified:true}).visualApproved,false));
test('actual_legacy_gable_regression_detected',()=>assert(old.maxExcessM>5&&old.status==='fail'));
const shiftedRoof=roof.map(tr=>tr.map(p=>[p[0]+10,p[1],p[2]]));test('roof_shift_fault_detected',()=>assert.equal(envelopeCheck([[.5,2,.5]],shiftedRoof).status,'unknown'));
test('triangle_order_independent',()=>assert.deepEqual(envelopeCheck([[.5,2.9,.5]],roof),envelopeCheck([[.5,2.9,.5]],roof.map(t=>[...t].reverse()))));
test('zero_bay_axis_rejected',()=>assert.throws(()=>axisCheck([0],[])));
test('known_failure_not_hidden_by_uncovered_sample',()=>assert.equal(envelopeCheck([[.5,3.3,.5],[3,2,3]],roof).status,'fail'));
const report={version:'0.2.0',auditVersion:AUDIT_VERSION,sourceCommit:process.env.GITHUB_SHA||'6998e63cb428c25d51761d95f5d00eab8c773004',legacySourceCommit:'6998e63cb428c25d51761d95f5d00eab8c773004',policyVersion:'1.0.0',stage:'first-building-evidence-and-control-preflight',newBuildingCompleted:false,legacyDefaultRetired:true,candidateId:c.id,candidateStatus:'dimensional-control-candidate_not_verified_historic_baseline',sourceIdentities:{generatorSha256:expected,casePath:cp,caseSha256:sha(path.join(app,cp)),sourceRegistryPath:ep,sourceRegistrySha256:sha(path.join(app,ep))},caseRecord:c,primarySources:sources,checks,release:releaseDecision(checks),legacyRegression:{...geom, ...old,drainage:drainageEvidence(geom.drainageDeclared,null),note:'检查限定旧北墙与主屋面下皮的几何矛盾，不推广为所有高墙规则。未执行完整降雨排水仿真。'},selfTests:{allPassed:tests.every(t=>t.passed),passed:tests.filter(t=>t.passed).length,total:tests.length,tests},next:['复核原始图纸及量距端点','确定完整剖面和两个相邻构架','核对节点、支承与可安装顺序','构架片段通过后扩为一栋','将墙体和瓦作作为独立接口接入'],unimplemented:['新栋完整几何','榫卯与构件截面真值','完整排水及承载验证','物理历史演化','跨Mother总装'],visualApproved:false,productionApproved:false};
fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({tests:report.selfTests,legacyWallPeakM:Math.max(...geom.points.map(p=>p[1])),maxExcessM:old.maxExcessM,caseChecks:checks.map(c=>({id:c.id,status:c.status})),approvals:report.release},null,2));
if(!report.selfTests.allPassed)process.exitCode=1;
