import { clamp } from './v26_transfer_kernel.mjs';

function hashInt(n){n=Math.imul(n^(n>>>16),0x7feb352d);n=Math.imul(n^(n>>>15),0x846ca68b);return(n^(n>>>16))>>>0}
export class RNG{constructor(seed=1){this.state=(seed>>>0)||1}next(){this.state=hashInt(this.state+0x9e3779b9);return this.state/0xffffffff}range(a,b){return a+(b-a)*this.next()}pick(a){return a[Math.min(a.length-1,Math.floor(this.next()*a.length))]}}
const FACES=['px','nx','py','ny','pz','nz'];
const N={px:[1,0,0],nx:[-1,0,0],py:[0,1,0],ny:[0,-1,0],pz:[0,0,1],nz:[0,0,-1]};
const add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]],mul=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];
function facePoint(face,h,r,m=.04){const p=[r.range(-h[0]+m,h[0]-m),r.range(-h[1]+m,h[1]-m),r.range(-h[2]+m,h[2]-m)];if(face==='px')p[0]=h[0];else if(face==='nx')p[0]=-h[0];else if(face==='py')p[1]=h[1];else if(face==='ny')p[1]=-h[1];else if(face==='pz')p[2]=h[2];else p[2]=-h[2];return p}
function tangent(face,r,s){return face[1]==='x'?[0,r.range(-s,s),r.range(-s,s)]:face[1]==='y'?[r.range(-s,s),0,r.range(-s,s)]:[r.range(-s,s),r.range(-s,s),0]}
export function sdEllipsoid(p,c,r){const x=(p[0]-c[0])/Math.max(r[0],1e-6),y=(p[1]-c[1])/Math.max(r[1],1e-6),z=(p[2]-c[2])/Math.max(r[2],1e-6);return(Math.hypot(x,y,z)-1)*Math.min(...r)}
export function sdCapsule(p,a,b,r){const pa=[p[0]-a[0],p[1]-a[1],p[2]-a[2]],ba=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],h=clamp((pa[0]*ba[0]+pa[1]*ba[1]+pa[2]*ba[2])/Math.max(1e-9,ba[0]**2+ba[1]**2+ba[2]**2));return Math.hypot(pa[0]-ba[0]*h,pa[1]-ba[1]*h,pa[2]-ba[2]*h)-r}

export function buildV26Events({dimensions=[3.083,1,2.013],runtimeDNA,noiseDNA,controls,seeds,damageLevel=.58}){
 const h=dimensions.map(v=>v*.5),minD=Math.min(...dimensions),dr=new RNG(seeds.damage^0x9e3779b9),pr=new RNG(seeds.pore^0x85ebca6b),wr=new RNG(seeds.weather^0xc2b2ae35),ir=new RNG(seeds.inclusion^0x27d4eb2d);
 const cd=clamp(damageLevel*.78+controls.damage*.62,0,1.75),density=.72+controls.poreDensity*.58,variety=.70+controls.poreVariety*.42;
 const counts={chips:Math.max(2,Math.round(1.4+runtimeDNA.edgeFragility*3.2+cd*5.1)),pits:Math.max(4,Math.round((2+runtimeDNA.pitDensity*3.7+cd*4.3)*density)),poreClusters:Math.max(8,Math.round((noiseDNA.geometryPoreCount??5)*(.66+damageLevel*.50+controls.poreDepth*.39)*density)),deepPores:Math.max(3,Math.round((noiseDNA.geometryDeepPoreCount??2.5)*(.50+controls.poreDepth*.74+damageLevel*.29)*(.78+controls.poreDensity*.44))),cracks:cd<.28?0:Math.max(1,Math.round(runtimeDNA.crackAffinity*1.4+cd*1.45)),erosionBites:Math.max(0,Math.round(controls.weathering*(.9+runtimeDNA.edgeFragility*1.7)+damageLevel*1.2)),inclusionVoids:Math.round(controls.inclusion*3.5)};
 const e={chips:[],pits:[],poreClusters:[],deepPores:[],poreRimChips:[],collapsedPores:[],cracks:[],erosionBites:[],inclusionVoids:[]};
 for(let i=0;i<counts.chips;i++){const f=dr.pick(FACES),c=facePoint(f,h,dr,minD*.05),s=minD*dr.range(.035,.14)*(.8+cd*.35);e.chips.push({face:f,center:add(c,mul(N[f],s*.18)),radii:[s*dr.range(.7,1.5),s*dr.range(.6,1.4),s*dr.range(.7,1.6)]})}
 for(let i=0;i<counts.pits;i++){const f=pr.pick(FACES),c=facePoint(f,h,pr,minD*.04),r=minD*pr.range(.012,.055)*variety;e.pits.push({face:f,center:add(c,mul(N[f],-r*.2)),radii:[r,r*pr.range(.45,1.15),r*pr.range(.45,1.15)]})}
 for(let i=0;i<counts.poreClusters;i++){const f=pr.pick(FACES),c=facePoint(f,h,pr,minD*.05),r=minD*pr.range(.014,.06)*variety;e.poreClusters.push({face:f,center:add(c,mul(N[f],-r*.16)),radii:[r*pr.range(.7,1.4),r*pr.range(.7,1.4),r*pr.range(.7,1.4)]})}
 for(let i=0;i<counts.deepPores;i++){const f=pr.pick(['px','nx','py','pz','nz']),n=N[f],sc=pr.next(),base=sc<.58?pr.range(.045,.09):sc<.86?pr.range(.09,.155):pr.range(.155,.245),r=minD*base*(.72+controls.poreDepth*.35),c=facePoint(f,h,pr,r*1.35),depth=minD*pr.range(.16,.62)*(.60+controls.poreDepth*.46),mouth=add(c,mul(n,-r*pr.range(.05,.28))),bore={face:f,a:add(c,mul(n,r*.2)),b:add(c,mul(n,-depth)),radius:r,mouthCenter:mouth,mouthRadii:[r*pr.range(1,1.5),r*pr.range(.75,1.25),r*pr.range(.75,1.25)],scaleClass:sc};e.deepPores.push(bore);const rc=Math.max(2,Math.round(pr.range(1.8,3.8)+controls.poreVariety*.95));for(let j=0;j<rc;j++){const rr=r*pr.range(.30,.68);e.poreRimChips.push({face:f,center:add(add(mouth,tangent(f,pr,r*pr.range(.72,1.36))),mul(n,r*pr.range(-.1,.1))),radii:[rr*pr.range(.7,1.4),rr*pr.range(.38,.72),rr*pr.range(.7,1.4)]})}if(sc>.80&&pr.next()<.36+controls.poreVariety*.20){const cr=r*pr.range(.72,1.18);e.collapsedPores.push({face:f,center:add(c,tangent(f,pr,r*.55)),radii:[cr*pr.range(1.1,1.65),cr*pr.range(.55,1.05),cr*pr.range(1.1,1.65)]})}}
 for(let i=0;i<counts.cracks;i++){const f=dr.pick(FACES),c=facePoint(f,h,dr,minD*.06),t=tangent(f,dr,minD*dr.range(.08,.25));e.cracks.push({face:f,a:add(add(c,mul(t,-.5)),mul(N[f],-minD*.01)),b:add(add(c,t),mul(N[f],-minD*.03)),radius:minD*dr.range(.005,.018)})}
 for(let i=0;i<counts.erosionBites;i++){const f=wr.pick(FACES),c=facePoint(f,h,wr,minD*.04),s=minD*wr.range(.06,.22)*(.65+controls.weathering*.35);e.erosionBites.push({face:f,center:add(c,mul(N[f],-s*.18)),radii:[s*wr.range(.8,1.7),s*wr.range(.5,1.4),s*wr.range(.8,1.7)]})}
 for(let i=0;i<counts.inclusionVoids;i++){const f=ir.pick(FACES),c=facePoint(f,h,ir,minD*.04),r=minD*ir.range(.015,.055);e.inclusionVoids.push({face:f,center:add(c,mul(N[f],-r*.12)),radii:[r*1.8,r*.55,r*.75]})}
 return e;
}
export function subtractV26Events(baseDistance,p,e){let d=baseDistance;for(const k of ['chips','pits','poreClusters','poreRimChips','collapsedPores','erosionBites','inclusionVoids'])for(const x of e[k])d=Math.max(d,-sdEllipsoid(p,x.center,x.radii));for(const x of e.deepPores){d=Math.max(d,-sdCapsule(p,x.a,x.b,x.radius));d=Math.max(d,-sdEllipsoid(p,x.mouthCenter,x.mouthRadii))}for(const x of e.cracks)d=Math.max(d,-sdCapsule(p,x.a,x.b,x.radius));return d}
export const V26_EVENT_LIBRARY=Object.freeze({version:'1.0.0-reference',events:['chips','pits','poreClusters','deepPores','poreRimChips','collapsedPores','cracks','erosionBites','inclusionVoids'],booleanRule:'d=max(d,-eventSdf)',boundary:'Brick Mother transfer semantics only'});
