'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path');let root=path.resolve(__dirname,'..'),C={console,performance};vm.createContext(C);vm.runInContext(['math.js','geometry.js'].map(f=>fs.readFileSync(root+'/source/'+f,'utf8')).join('\n')+'\nthis.A={ceramic,timber,M,model,SEATS,tileModel};',C);let A=C.A,pan=A.ceramic('pan'),cover=A.ceramic('cover'),S=A.SEATS;
function triangles(mesh,m){let p=[];for(let i=0;i<mesh.p.length;i+=3)p.push(A.M.transform(m,[...mesh.p.slice(i,i+3)]));let out=[];for(let j=0;j<mesh.idx.length;j+=3){let v=[...mesh.idx.slice(j,j+3)].map(i=>p[i]),a=v[0],b=v[1],c=v[2],d=(b[0]-a[0])*(c[2]-a[2])-(b[2]-a[2])*(c[0]-a[0]);if(Math.abs(d)<1e-13)continue;let fy=((b[1]-a[1])*(c[2]-a[2])-(c[1]-a[1])*(b[2]-a[2]))/d,fz=((b[0]-a[0])*(c[1]-a[1])-(c[0]-a[0])*(b[1]-a[1]))/d;out.push({v:v.map(p=>[p[0],p[2]]),sgn:Math.sign(d),xmin:Math.min(...v.map(p=>p[0])),xmax:Math.max(...v.map(p=>p[0])),zmin:Math.min(...v.map(p=>p[2])),zmax:Math.max(...v.map(p=>p[2])),y:(x,z)=>a[1]+fy*(x-a[0])+fz*(z-a[2])});}return out}
function intersect(a,b){let poly=a.v;for(let j=0;j<3;j++){let p=b.v[j],q=b.v[(j+1)%3],sign=b.sgn,dist=v=>sign*((q[0]-p[0])*(v[1]-p[1])-(q[1]-p[1])*(v[0]-p[0])),out=[];for(let k=0;k<poly.length;k++){let v=poly[k],w=poly[(k+1)%poly.length],d=dist(v),e=dist(w),inside=d>=-1e-12,next=e>=-1e-12;if(inside)out.push(v);if(inside!==next){let t=d/(d-e);out.push([v[0]+t*(w[0]-v[0]),v[1]+t*(w[1]-v[1])])}}poly=out;if(poly.length<3)return[]}return poly}
function gap(name,lower,lm,upper,um){let L=triangles(lower,lm),U=triangles(upper,um),min=Infinity,count=0,where=null;for(let a of L)for(let b of U){if(a.xmin>b.xmax||a.xmax<b.xmin||a.zmin>b.zmax||a.zmax<b.zmin)continue;let poly=intersect(a,b);if(poly.length<3)continue;count++;for(let [x,z]of poly){let d=b.y(x,z)-a.y(x,z);if(d<min){min=d;where=[x,z]}}}return{name,trianglePairs:count,minGapMm:Number.isFinite(min)?min*1000:null,where,pass:count===0||min>=-.00005}}
if(process.env.CONTACT_LIB){module.exports={A,pan,cover,S,gap,auditTriangles:triangles};return;}
let tests=[],wood=A.timber(),tile=A.tileModel;
for(let kind of ['pan','cover']){let mesh=kind==='pan'?pan:cover,Y=kind==='pan'?S.panY:S.coverY;tests.push(gap(kind+' longitudinal',mesh,tile(kind,0,Y,0),mesh,tile(kind,0,Y,S.step)))}
for(let side of[-1,1])for(let row of[-1,0,1])tests.push(gap('cover on pan '+side+'/'+row,pan,tile('pan',side*S.spacing*.5,S.panY,row*S.step),cover,tile('cover',0,S.coverY,S.coverPhase)));
for(let side of[-1,1])for(let z of[-1.8,0,1.8])tests.push(gap('rafter-pan '+side+'/'+z,wood,A.model(side*S.spacing*.5,0,0,0,0,[S.rafterRadius,S.rafterRadius,4.02]),pan,tile('pan',0,S.panY,z)));
tests.push(gap('crossbeam-rafter',wood,A.model(0,-S.rafterRadius-.037,0,0,Math.PI/2,[.037,.037,5.4]),wood,A.model(0,0,0,0,0,[S.rafterRadius,S.rafterRadius,4.02])));
let bilateral=tests.filter(x=>x.name.startsWith('rafter-pan')||/cover on pan [-1]+\/0/.test(x.name)).every(t=>t.minGapMm<=.5);
let report={scope:'Projected triangle intersections evaluated with affine height on every intersection vertex. Shared rigid templates only. No load capacity, moss-on-surface, arbitrary fracture motion or debris collision.',toleranceMm:.05,bilateralMaxMm:.5,seats:S,tests,bilateralPassed:bilateral,pass:tests.every(t=>t.pass)&&bilateral};fs.writeFileSync(root+'/qa/CONTACT.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
