/* Tiles Mother V0.2 reference desk. Original files stay local and byte-identical. */
const R = window.TilesReferenceRuntime;
const REF_LIMIT = 512 * 1024 * 1024, TOTAL_LIMIT = 2 * 1024 * 1024 * 1024, MAX_REFS = 2000;
const MODEL_EXT = new Set(['glb','gltf','fbx','obj','stl','ply','dae','3mf']);
const IMAGE_EXT = new Set(['png','jpg','jpeg','webp','gif','bmp','avif','svg','ico']);
const TEXT_EXT = new Set(['txt','md','json','csv','tsv','xml','yaml','yml','mtl','html','htm','log','ini']);
const MIME = {png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif',bmp:'image/bmp',avif:'image/avif',svg:'image/svg+xml',ico:'image/x-icon',pdf:'application/pdf',glb:'model/gltf-binary',gltf:'model/gltf+json',zip:'application/zip',mp4:'video/mp4',webm:'video/webm',mp3:'audio/mpeg',wav:'audio/wav',ogg:'audio/ogg'};
let ingestTail=Promise.resolve(), refViewer=null, previewSerial=0, noteTimer=0, ingestBusy=false, pendingRefWrites=new Set();
let previewState={status:'empty'}, currentPreviewId=null;
const extOf=name=>String(name||'').split('.').pop().toLowerCase();
const bytesLabel=n=>n>=1024**3?(n/1024**3).toFixed(2)+' GB':n>=1024**2?(n/1024**2).toFixed(2)+' MB':n>=1024?(n/1024).toFixed(1)+' KB':n+' B';
const kindOf=(name,mime='')=>{const e=extOf(name);return MODEL_EXT.has(e)?'model':IMAGE_EXT.has(e)?'image':e==='pdf'?'pdf':TEXT_EXT.has(e)?'text':mime.startsWith('video/')||['mp4','webm','mov','m4v'].includes(e)?'video':mime.startsWith('audio/')||['mp3','wav','ogg','m4a','flac'].includes(e)?'audio':['zip','7z','rar','tar','gz'].includes(e)?'archive':'file';};
const pause=()=>new Promise(r=>setTimeout(r,0));
function safePath(input){let p=String(input||'reference').replace(/\\/g,'/').replace(/^\.\//,'');if(p.includes('\0')||p.startsWith('/')||/^[a-z]:/i.test(p)||p.split('/').includes('..'))throw Error('资料路径无效：'+p.slice(0,120));return p.split('/').filter(x=>x&&x!=='.').join('/')||'reference';}
function normalizeRef(r){return {...r,kind:r.kind||kindOf(r.filename,r.mime),relativePath:r.relativePath||r.filename,bundleId:r.bundleId||'legacy',persisted:true,url:URL.createObjectURL(r.blob)};}
function openDB(){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error('IndexedDB unavailable'));const q=indexedDB.open('TilesMotherStudioV01',1);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains('project'))d.createObjectStore('project');if(!d.objectStoreNames.contains('refs'))d.createObjectStore('refs',{keyPath:'id'});};q.onsuccess=()=>{q.result.onversionchange=()=>{q.result.close();db=null;dbReady=false;fallback=true;storageStatus();};resolve(q.result);};q.onerror=()=>reject(q.error);q.onblocked=()=>reject(Error('请关闭其他旧版工作台后重新打开。'));});}
function requestDB(store,mode,fn){return new Promise((resolve,reject)=>{if(!db)return reject(Error('storage unavailable'));const tx=db.transaction(store,mode),q=fn(tx.objectStore(store));let result;q.onsuccess=()=>{result=q.result;};q.onerror=()=>reject(q.error);tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('storage aborted'));});}
function stripRef(r){const {url,persisted,...rest}=r;return rest;}
function refMetadata(r){const {blob,url,persisted,...meta}=r;return clone(meta);}
function storageStatus(){const volatile=refs.filter(x=>!x.persisted).length;$('storageHint').textContent=volatile||!db?'有 '+(volatile||refs.length)+' 份资料暂留内存。请保存协作包并保留原文件，关闭页面前不要清理浏览器。资料不会自动发送到聊天。':'原文件与笔记保存在当前浏览器，不会自动上传到服务器或聊天。用“保存协作包”携带原文件、参数和笔记；清除浏览器数据会清除本地资料。';$('storageHint').classList.toggle('storage-warning',!!volatile||!db);}
function saveSoon(){dirty=true;$('saveStatus').textContent=fallback?'请保留协作包备份':'正在保存到此浏览器';clearTimeout(saveTimer);saveTimer=setTimeout(saveProject,500);}
async function saveProject(){if(!db)return;try{project.visualApproved=false;project.productionApproved=false;await requestDB('project','readwrite',s=>s.put(clone(project),'current'));dirty=false;$('saveStatus').textContent='已保存到此浏览器 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});}catch(e){fallback=true;$('saveStatus').textContent='本地空间不足，请保存协作包';}storageStatus();}
function validateProject(raw){if(!raw||raw.schema!=='tiles-mother-project'||!['0.1.0','0.2.0'].includes(raw.version))throw Error('无法识别协作记录版本。支持 V0.1 和 V0.2。');const p=newProject();if(Object.hasOwn(PROFILE_DEFS,raw.active))p.active=raw.active;p.selectedChild=[0,1,2].includes(raw.selectedChild)?raw.selectedChild:0;p.layout=['single','trio'].includes(raw.layout)?raw.layout:'single';p.channel=['final','source','albedo','normal','cavity','roughness','weather','macro','meso'].includes(raw.channel)?raw.channel:'final';for(const k of Object.keys(PROFILE_DEFS)){const r=raw.profiles?.[k];if(!r)continue;for(const [key,,min,max]of [...SHAPE,...MATERIAL]){const v=Number(r.controls?.[key]);if(Number.isFinite(v))p.profiles[k].controls[key]=clamp(v,min,max);}if(['grey','red','green','ivory'].includes(r.controls?.palette))p.profiles[k].controls.palette=r.controls.palette;for(const key of ['master',...Object.keys(SEED_LABELS)])if(r.seeds?.[key]!==undefined)p.profiles[k].seeds[key]=safeSeed(r.seeds[key]);}return p;}
/* Streaming SHA-256 avoids materializing very large reference files just to hash them. */
class RefSHA256 {
 constructor(){this.h=new Uint32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]);this.buffer=new Uint8Array(64);this.used=0;this.length=0;this.w=new Uint32Array(64);}
 block(a){const w=this.w;for(let i=0;i<16;i++)w[i]=(a[i*4]<<24)|(a[i*4+1]<<16)|(a[i*4+2]<<8)|a[i*4+3];const rr=(x,n)=>(x>>>n)|(x<<(32-n));for(let i=16;i<64;i++){const x=w[i-15],y=w[i-2];w[i]=(w[i-16]+(rr(x,7)^rr(x,18)^(x>>>3))+w[i-7]+(rr(y,17)^rr(y,19)^(y>>>10)))>>>0;}let [a0,b,c,d,e,f,g,h]=this.h;for(let i=0;i<64;i++){const t1=(h+(rr(e,6)^rr(e,11)^rr(e,25))+((e&f)^(~e&g))+RefSHA256.K[i]+w[i])>>>0,t2=((rr(a0,2)^rr(a0,13)^rr(a0,22))+((a0&b)^(a0&c)^(b&c)))>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a0;a0=(t1+t2)>>>0;}const out=[a0,b,c,d,e,f,g,h];for(let i=0;i<8;i++)this.h[i]=(this.h[i]+out[i])>>>0;}
 update(a){this.length+=a.length;let p=0;while(p<a.length){const n=Math.min(64-this.used,a.length-p);this.buffer.set(a.subarray(p,p+n),this.used);p+=n;this.used+=n;if(this.used===64){this.block(this.buffer);this.used=0;}}}
 hex(){const bitLength=this.length*8;this.buffer[this.used++]=0x80;if(this.used>56){this.buffer.fill(0,this.used);this.block(this.buffer);this.used=0;}this.buffer.fill(0,this.used,56);const dv=new DataView(this.buffer.buffer);dv.setUint32(56,Math.floor(bitLength/4294967296));dv.setUint32(60,bitLength>>>0);this.block(this.buffer);return [...this.h].map(v=>v.toString(16).padStart(8,'0')).join('');}
}
RefSHA256.K=new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]);
async function sha256(blob){if(crypto?.subtle&&blob.size<32*1024*1024){const h=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer());return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');}const h=new RefSHA256();for(let offset=0;offset<blob.size;offset+=1024*1024){h.update(new Uint8Array(await blob.slice(offset,offset+1024*1024).arrayBuffer()));await pause();}return h.hex();}
function imageMeta(blob){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(blob),img=new Image(),timer=setTimeout(()=>done(Error('图片解码超时，原文件已保留。')),20000);function done(error){clearTimeout(timer);URL.revokeObjectURL(url);img.onload=img.onerror=null;error?reject(error):resolve({width:img.naturalWidth,height:img.naturalHeight});}img.onload=()=>done();img.onerror=()=>done(Error('当前浏览器无法预览这张图片，原文件已保留。'));img.src=url;});}
function ingestMessage(lines){$('ingestReport').textContent=lines.join('\n');$('ingestReport').classList.toggle('hidden',!lines.length);}
async function saveRefRecord(record){record.persisted=false;if(db){try{await requestDB('refs','readwrite',s=>s.put(stripRef(record)));record.persisted=true;}catch(e){fallback=true;}}return record;}
function addFiles(files,options={}){const entries=[...files].map(x=>x.file?x:{file:x,path:x.webkitRelativePath||x.name||'clipboard.png'});ingestTail=ingestTail.catch(()=>{}).then(()=>ingestEntries(entries,options));return ingestTail;}
async function ingestEntries(entries,options={}){
 if(!entries.length)return;ingestBusy=true;$('dropTitle').textContent='正在保存原文件';const messages=[],bundleId=options.bundleId||makeId();let added=[],total=refs.reduce((n,r)=>n+r.size,0),expanded=[];
 try{for(let i=0;i<entries.length;i++){const {file}=entries[i];let path;try{path=safePath(entries[i].path||file.name);if(!(file instanceof Blob))throw Error('文件内容不可读取。');if(file.size>REF_LIMIT)throw Error('单文件超过 512 MB 安全上限，请保留原件并分批提供。');if(total+file.size>TOTAL_LIMIT||refs.length>=MAX_REFS)throw Error('本地资料达到安全上限，请先保存协作包。');$('ingestProgress').textContent=(i+1)+' / '+entries.length+' · '+path;const hash=await sha256(file);const duplicate=refs.find(r=>r.sha256===hash&&r.relativePath===path);if(duplicate){messages.push(path+'：原文件已存在');continue;}
 const filename=path.split('/').pop(),mime=file.type||MIME[extOf(filename)]||'application/octet-stream',blob=file.type===mime?file:new Blob([file],{type:mime});const record={id:makeId(),title:filename,filename,relativePath:path,bundleId,mime,size:file.size,blob,sha256:hash,kind:kindOf(filename,mime),type:project.active,source:'',notes:'',status:'pending',createdAt:new Date().toISOString()};
 await saveRefRecord(record);record.url=URL.createObjectURL(blob);refs.push(record);added.push(record);total+=record.size;
 if(record.kind==='image'){try{Object.assign(record,await imageMeta(blob));await saveRefRecord(record);}catch(error){record.previewNote=error.message;}}
 messages.push(path+'：'+(record.persisted?'已保存':'暂留内存')+' · '+bytesLabel(record.size));
 if(extOf(filename)==='zip'&&!options.noUnpack){try{const unpacked=await unpackZip(blob);const prefix=path.replace(/\.zip$/i,'')+'/';for(const [name,data]of Object.entries(unpacked)){if(name.endsWith('/')||name.startsWith('__MACOSX/')||name.split('/').pop()==='.DS_Store')continue;expanded.push({file:new File([data],name.split('/').pop(),{type:MIME[extOf(name)]||''}),path:prefix+safePath(name)});}messages.push('ZIP：原包完整保留，展开 '+expanded.length+' 个配套文件。');}catch(error){messages.push('ZIP 已保留；未展开：'+error.message);}}
 }catch(error){messages.push((path||file?.name||'资料')+'：'+error.message);}}
 selectedRef=(added.find(r=>r.kind==='model')||added.find(r=>r.kind==='image')||added.at(-1))?.id||selectedRef;
 if(expanded.length){await ingestEntries(expanded,{bundleId,noUnpack:true});}
 else{renderRefs(true);}
 if(added.length)toast('已接收 '+added.length+' 份原文件。'+(expanded.length?'配套文件已一并展开。':''));
 }finally{ingestBusy=false;$('dropTitle').textContent='拖入模型、图片或任意资料';$('ingestProgress').textContent='GLB / FBX / 文件夹 / ZIP · 格式不限';$('refFiles').value='';$('refFolders').value='';ingestMessage(messages);storageStatus();}
}
/* Validate ZIP central directory before allocating expanded data. Unsupported archives stay intact. */
async function zipDirectory(blob){if(blob.size>REF_LIMIT)throw Error('ZIP 超过 512 MB。');const tail=new Uint8Array(await blob.slice(Math.max(0,blob.size-65558)).arrayBuffer()),view=new DataView(tail.buffer);let e=-1;for(let p=tail.length-22;p>=0;p--)if(view.getUint32(p,true)===0x06054b50){e=p;break;}if(e<0)throw Error('未找到 ZIP 目录。');const count=view.getUint16(e+10,true),size=view.getUint32(e+12,true),offset=view.getUint32(e+16,true);if(count===65535||size===0xffffffff||offset===0xffffffff)throw Error('ZIP64 暂存原包，当前不自动展开。');if(count>MAX_REFS||size>16*1024*1024||offset+size>blob.size)throw Error('ZIP 目录超出安全范围。');const bytes=new Uint8Array(await blob.slice(offset,offset+size).arrayBuffer()),dv=new DataView(bytes.buffer),names=new Set();let p=0,total=0;for(let i=0;i<count;i++){if(p+46>bytes.length||dv.getUint32(p,true)!==0x02014b50)throw Error('ZIP 目录损坏。');const flags=dv.getUint16(p+8,true),compressed=dv.getUint32(p+20,true),uncompressed=dv.getUint32(p+24,true),nl=dv.getUint16(p+28,true),extra=dv.getUint16(p+30,true),comment=dv.getUint16(p+32,true);if(flags&1)throw Error('加密 ZIP 已保存，请先解密后拖入。');if(p+46+nl+extra+comment>bytes.length)throw Error('ZIP 目录不完整。');const name=new TextDecoder().decode(bytes.subarray(p+46,p+46+nl));safePath(name);if(names.has(name))throw Error('ZIP 存在重复路径。');names.add(name);total+=uncompressed;if(uncompressed>REF_LIMIT||total>768*1024*1024||(uncompressed>10*1024*1024&&uncompressed/Math.max(1,compressed)>1000))throw Error('ZIP 展开体积超出安全范围，原包已保留。');p+=46+nl+extra+comment;}return {count,total};}
async function unpackZip(blob){if(!R?.archive)throw Error('归档组件尚未就绪。');await zipDirectory(blob);const data=new Uint8Array(await blob.arrayBuffer());return new Promise((resolve,reject)=>R.archive.unzip(data,{filter:f=>f.originalSize<=REF_LIMIT},(error,files)=>error?reject(error):resolve(files)));}
async function droppedEntries(transfer){const roots=[...(transfer.items||[])].filter(i=>i.kind==='file').map(i=>({entry:i.webkitGetAsEntry?.(),file:i.getAsFile()}));const out=[];async function walk(entry,prefix=''){if(out.length>=MAX_REFS)throw Error('文件夹超过 2000 个文件，请分批拖入。');if(entry.isFile){const file=await new Promise((resolve,reject)=>entry.file(resolve,reject));out.push({file,path:prefix+entry.name});}else if(entry.isDirectory){const reader=entry.createReader();for(;;){const list=await new Promise((resolve,reject)=>reader.readEntries(resolve,reject));if(!list.length)break;for(const child of list)await walk(child,prefix+entry.name+'/');}}}for(const root of roots){if(root.entry)await walk(root.entry);else if(root.file)out.push({file:root.file,path:root.file.name});}return out.length?out:[...transfer.files].map(file=>({file,path:file.name}));}
function activeRef(){return refs.find(r=>r.id===selectedRef)||refs[0];}
function renderRefs(force=false){const r=activeRef();$('refCount').textContent=refs.length+' 份';$('emptyRefs').classList.toggle('hidden',!!r);$('refEditor').classList.toggle('hidden',!r);$('refThumbs').replaceChildren();if(!r){previewSerial++;previewState={status:'empty'};refViewer?.clear();currentPreviewId=null;return;}selectedRef=r.id;for(const item of refs){const b=document.createElement('button');b.className='thumb'+(r.id===item.id?' active':'');b.title=item.relativePath||item.title;b.setAttribute('aria-label',item.title);if(item.kind==='image'&&item.width){const img=document.createElement('img');img.src=item.url;img.alt=item.title;img.loading='lazy';b.append(img);}else{const tag=document.createElement('strong');tag.textContent=extOf(item.filename).slice(0,6).toUpperCase();const sub=document.createElement('small');sub.textContent=item.kind==='model'?'三维':item.kind==='archive'?'资料包':'资料';b.append(tag,sub);}b.onclick=()=>{flushRefNotes();selectedRef=item.id;renderRefs();};$('refThumbs').append(b);}
 $('refTitle').value=r.title;$('refType').value=r.type;$('refSource').value=r.source;$('refNotes').value=r.notes;$('refDimensions').textContent=(r.width?r.width+' × '+r.height+' px · ':'')+bytesLabel(r.size);$('refPath').textContent=r.relativePath;$('refHash').textContent='SHA256 '+r.sha256;$('refPersistence').textContent=r.persisted?'原文件已保存到本浏览器':'原文件暂留内存，请保存协作包';$('refPersistence').classList.toggle('storage-warning',!r.persisted);if(force||currentPreviewId!==r.id){currentPreviewId=r.id;showReference(r);}storageStatus();}
function flushRefNotes(){clearTimeout(noteTimer);const r=activeRef();if(!r)return Promise.resolve();const task=saveRefRecord(r).then(()=>{storageStatus();});pendingRefWrites.add(task);task.finally(()=>pendingRefWrites.delete(task));return task;}
function editRef(){const r=activeRef();if(!r)return;r.title=$('refTitle').value;r.type=$('refType').value;r.source=$('refSource').value;r.notes=$('refNotes').value;clearTimeout(noteTimer);noteTimer=setTimeout(()=>{flushRefNotes();$('saveStatus').textContent='参考笔记已更新';},350);}
function setPreviewNotice(message,state='saved'){const el=$('previewNotice');el.textContent=message;el.className='preview-notice '+state;}
async function showReference(r){const serial=++previewSerial;previewState={status:'loading',id:r.id,kind:r.kind};restoreModelStage();refViewer?.clear();for(const id of ['enlargeRef','modelStage','fileStage'])$(id).classList.add('hidden');$('previewText').replaceChildren();$('mediaStage').replaceChildren();$('modelStats').textContent='';$('modelWarnings').textContent='';setPreviewNotice('原文件已接收，正在准备预览。','loading');
 if(r.kind==='model'){try{if(!R)throw Error('三维读取组件未就绪。原文件仍然保留。');$('modelStage').classList.remove('hidden');if(!refViewer)refViewer=new ReferenceViewer($('referenceCanvas'));await refViewer.load(r,()=>serial===previewSerial);if(serial!==previewSerial)return;previewState={status:'ready',id:r.id,kind:r.kind,...refViewer.stats};setPreviewNotice(refViewer.warnings.length?'模型可观察，配套资源需要补齐。':'模型已载入 · 拖动旋转，滚轮缩放','ready');$('modelWarnings').textContent=refViewer.warnings.join('\n');}catch(error){if(serial!==previewSerial)return;previewState={status:'error',id:r.id,error:String(error.message)};setPreviewNotice('原文件已保留。预览提示：'+error.message,'warning');}return;}
 if(r.kind==='image'&&r.width){$('activeRefImg').src=r.url;$('activeRefImg').alt=r.title;$('enlargeRef').classList.remove('hidden');setPreviewNotice('原图完整保留 · 点击图片放大','ready');previewState={status:'ready',id:r.id,kind:'image'};return;}
 $('fileStage').classList.remove('hidden');$('fileIcon').textContent=extOf(r.filename).toUpperCase().slice(0,8)||'FILE';$('fileStageName').textContent=r.filename;
 if(r.kind==='text'){const text=await r.blob.slice(0,160*1024).text();if(serial!==previewSerial)return;$('previewText').textContent=text+(r.size>160*1024?'\n\n这里只展示前 160 KB，原文件完整保留。':'');setPreviewNotice('文本安全预览 · 不执行其中的代码','ready');}
 else if(['video','audio'].includes(r.kind)){const media=document.createElement(r.kind);media.controls=true;media.preload='metadata';media.src=r.url;media.onloadedmetadata=()=>{if(serial===previewSerial)setPreviewNotice('媒体可预览，原文件完整保留。','ready');};media.onerror=()=>{if(serial===previewSerial)setPreviewNotice('当前浏览器不支持这个媒体编码，原文件完整保留。','warning');};$('mediaStage').append(media);setPreviewNotice('媒体原件已保存，播放能力取决于浏览器。');}
 else if(r.kind==='pdf'){const a=document.createElement('a');a.textContent='在新窗口查看 PDF';a.href=r.url;a.target='_blank';a.rel='noopener noreferrer';a.className='file-open-link';$('mediaStage').append(a);setPreviewNotice('PDF 原件已保存，可用浏览器打开查看。');}
 else setPreviewNotice(r.previewNote||(r.kind==='archive'?'原始资料包已保存。ZIP 可自动展开，其他归档格式保留原包。':'原文件已保存。这个格式目前作为资料收存，暂未接入直接预览。'));
 previewState={status:'saved',id:r.id,kind:r.kind};
}
function disposeObject(root){if(!root)return;const geo=new Set(),mats=new Set(),textures=new Set();root.traverse(o=>{if(o.geometry)geo.add(o.geometry);for(const m of [].concat(o.material||[])){mats.add(m);for(const value of Object.values(m))if(value?.isTexture)textures.add(value);}});geo.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());textures.forEach(t=>{t.dispose();t.source?.data?.close?.();});}
const transparentPixel='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4////fwAJ+wP9KobjigAAAABJRU5ErkJggg==';
class ReferenceViewer {
 constructor(canvas){this.canvas=canvas;this.renderer=new R.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.outputColorSpace=R.SRGBColorSpace;this.renderer.toneMapping=R.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.scene=new R.Scene();this.scene.background=new R.Color(0xe3e6de);this.camera=new R.PerspectiveCamera(42,1,.01,100);this.controls=new R.OrbitControls(this.camera,canvas);this.controls.enableDamping=false;this.controls.minDistance=.04;this.controls.maxDistance=30;this.controls.addEventListener('change',()=>this.draw());this.scene.add(new R.HemisphereLight(0xffffff,0x7f8876,2.2));for(const [x,y,z,p]of [[3,5,4,3],[-4,2,-3,1.4]]){const light=new R.DirectionalLight(0xffffff,p);light.position.set(x,y,z);this.scene.add(light);}this.buildEnvironment();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement);this.originals=new Map();this.mode='original';this.warnings=[];this.decoderURLs=[];this.initDecoders();this.fit();canvas.addEventListener('dblclick',()=>this.fit());canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();setPreviewNotice('三维上下文被浏览器释放。原文件已保留，请重新打开工作台。','warning');});}
 buildEnvironment(){const envScene=new R.Scene();envScene.background=new R.Color(0xc9cdc6);for(const [x,y,z,sx,sy,sz,c]of [[0,4,0,8,.1,8,0xffffff],[-4,0,0,.1,8,8,0xc6d1d7],[4,0,0,.1,8,8,0xd6ccb8],[0,0,-4,8,8,.1,0xc7cfc2]]){const mesh=new R.Mesh(new R.BoxGeometry(sx,sy,sz),new R.MeshBasicMaterial({color:c}));mesh.position.set(x,y,z);envScene.add(mesh);}const gen=new R.PMREMGenerator(this.renderer);this.environment=gen.fromScene(envScene,.04);this.scene.environment=this.environment.texture;gen.dispose();disposeObject(envScene);}
 initDecoders(){const data=JSON.parse($('tm-decoder-assets')?.textContent||'{}');const manager=new R.LoadingManager();manager.setURLModifier(url=>{const name=url.split('/').pop();if(!data[name])throw Error('缺少压缩模型解码器 '+name);const raw=atob(data[name]),array=Uint8Array.from(raw,c=>c.charCodeAt(0));const objectURL=URL.createObjectURL(new Blob([array],{type:name.endsWith('.wasm')?'application/wasm':'text/javascript'}));this.decoderURLs.push(objectURL);return objectURL;});this.draco=new R.DRACOLoader(manager).setDecoderPath('tm-decoder/').setDecoderConfig({type:'wasm'}).setWorkerLimit(2);this.ktx2=new R.KTX2Loader(manager).setTranscoderPath('tm-decoder/').setWorkerLimit(2).detectSupport(this.renderer);}
 resize(){const rect=this.canvas.parentElement.getBoundingClientRect();if(rect.width<2||rect.height<2)return;this.renderer.setSize(rect.width,rect.height,false);this.camera.aspect=rect.width/rect.height;this.camera.updateProjectionMatrix();this.draw();}
 draw(){if(this.canvas.parentElement.getBoundingClientRect().width>1)this.renderer.render(this.scene,this.camera);}
 fit(){const a=Math.max(.1,this.camera.aspect),vfov=42*Math.PI/180,hfov=2*Math.atan(Math.tan(vfov/2)*a),d=1.55/Math.sin(Math.min(vfov,hfov)/2);this.camera.position.set(d*.72,d*.46,d*.72);this.controls.target.set(0,0,0);this.controls.update();this.draw();}
 clear(){if(this.root){this.setMode('original');this.scene.remove(this.root);disposeObject(this.root);this.root=null;}this.originals?.clear();this.stats=null;this.draw();}
 setMode(mode){this.mode=mode;if(!this.root)return;this.root.traverse(o=>{if(!o.isMesh)return;if(!this.originals.has(o))this.originals.set(o,o.material);if(o.material!==this.originals.get(o))for(const m of [].concat(o.material))m.dispose();o.material=mode==='original'?this.originals.get(o):new R.MeshStandardMaterial({color:0xc3c5b8,metalness:0,roughness:.85,wireframe:mode==='wire',side:R.DoubleSide});});this.draw();}
 resourceManager(record){const created=[],missing=new Set(),ambiguous=new Set();let allDone;const complete=new Promise(r=>allDone=r);const manager=new R.LoadingManager(()=>{allDone();this.draw();});manager.addHandler(/\.tga($|\?)/i,new R.TGALoader(manager));manager.addHandler(/\.dds($|\?)/i,new R.DDSLoader(manager));const normalize=p=>{try{p=decodeURIComponent(p);}catch{}return String(p).replace(/\\/g,'/').replace(/[?#].*$/,'').replace(/^file:\/\/*/i,'').replace(/^\.\//,'');};const dirname=(record.relativePath||record.filename).split('/').slice(0,-1).join('/');
 const resolve=url=>{if(/^(blob:|data:)/i.test(url))return url;const raw=normalize(url),candidate=raw.startsWith('tm-local/')?raw.slice(9):raw,base=candidate.split('/').pop().toLowerCase();let choices=refs.filter(r=>normalize(r.relativePath).toLowerCase()===candidate.toLowerCase());if(!choices.length&&dirname)choices=refs.filter(r=>normalize(r.relativePath).toLowerCase()===(dirname+'/'+candidate).toLowerCase());if(!choices.length)choices=refs.filter(r=>r.filename.toLowerCase()===base);const same=choices.filter(r=>r.bundleId===record.bundleId);if(same.length)choices=same;if(choices.length===1){const u=URL.createObjectURL(choices[0].blob);created.push(u);return u;}if(choices.length>1)ambiguous.add(candidate);else missing.add(candidate);if(/\.(bin|buffer)($|\?)/i.test(candidate))throw Error('缺少或无法唯一匹配配套数据：'+candidate+'。请把完整文件夹一起拖入。');return transparentPixel;};
 manager.setURLModifier(resolve);manager.onError=url=>missing.add(normalize(url));manager.itemStart('tm-root');return {manager,complete,done:()=>manager.itemEnd('tm-root'),dispose:()=>created.forEach(u=>URL.revokeObjectURL(u)),warnings:()=>[...missing].map(p=>'缺少配套资源：'+p+'。可继续补入原文件。').concat([...ambiguous].map(p=>'存在同名资源：'+p+'。请用文件夹或 ZIP 保留目录。'))};}
 async load(record,isCurrent){this.clear();this.warnings=[];const context=this.resourceManager(record),ext=extOf(record.filename),buffer=await record.blob.arrayBuffer();let object;try{if(!isCurrent())return;const text=()=>new TextDecoder().decode(buffer);const base='tm-local/'+((record.relativePath||'').split('/').slice(0,-1).join('/')?((record.relativePath||'').split('/').slice(0,-1).join('/')+'/'):'');
 if(ext==='glb'||ext==='gltf'){const result=await new R.GLTFLoader(context.manager).setDRACOLoader(this.draco).setKTX2Loader(this.ktx2).setMeshoptDecoder(R.MeshoptDecoder).parseAsync(ext==='gltf'?text():buffer,base);object=result.scene;}
 else if(ext==='fbx')object=new R.FBXLoader(context.manager).parse(buffer,base);
 else if(ext==='obj'){const loader=new R.OBJLoader(context.manager),src=text(),match=/^mtllib\s+(.+)$/mi.exec(src);if(match){const name=match[1].trim();const exact=refs.filter(r=>r.kind==='text'&&extOf(r.filename)==='mtl'&&(r.relativePath===base.slice(9)+name||r.filename===name));const same=exact.filter(r=>r.bundleId===record.bundleId),mtl=(same.length===1?same:exact.length===1?exact:[])[0];if(mtl){const materials=new R.MTLLoader(context.manager).parse(await mtl.blob.text(),base);materials.preload();loader.setMaterials(materials);}else this.warnings.push('配套 MTL 未找到：'+name+'。当前显示基础材质。');}object=loader.parse(src);}
 else if(ext==='stl'||ext==='ply'){const geometry=ext==='stl'?new R.STLLoader(context.manager).parse(buffer):new R.PLYLoader(context.manager).parse(buffer);if(!geometry.attributes.normal)geometry.computeVertexNormals();const material=new R.MeshStandardMaterial({color:geometry.hasAttribute('color')?0xffffff:0xaaa996,vertexColors:geometry.hasAttribute('color'),roughness:.85,side:R.DoubleSide});object=new R.Mesh(geometry,material);}
 else if(ext==='dae')object=new R.ColladaLoader(context.manager).parse(text(),base).scene;
 else if(ext==='3mf')object=new R.ThreeMFLoader(context.manager).parse(buffer);
 else throw Error('该格式暂未接入三维预览。');
 }catch(error){context.dispose();throw error;}finally{context.done();}
 try{await Promise.race([context.complete,new Promise((_,reject)=>setTimeout(()=>reject(Error('配套资源读取超时。原文件已保留，可重新预览。')),30000))]);if(!isCurrent()){disposeObject(object);return;}if(!object)throw Error('文件没有可预览的场景。');object.updateMatrixWorld(true);const box=new R.Box3().setFromObject(object),size=new R.Vector3(),center=new R.Vector3();box.getSize(size);box.getCenter(center);const max=Math.max(size.x,size.y,size.z);if(!Number.isFinite(max)||max<=0)throw Error('未发现具有有效尺寸的表面网格。原文件和动画数据均已保留。');let triangles=0,meshes=0,vertices=0;object.traverse(o=>{if(o.isMesh){meshes++;const g=o.geometry;vertices+=(g.attributes.position?.count||0)*(o.count||1);triangles+=Math.floor((g.index?.count||g.attributes.position?.count||0)/3)*(o.count||1);}if(o.isLight)o.visible=false;});this.root=new R.Group();this.root.add(object);this.root.scale.setScalar(2/max);this.root.position.copy(center).multiplyScalar(-2/max);this.scene.add(this.root);this.stats={meshes,triangles,vertices,dimensions:[size.x,size.y,size.z],unit:ext==='glb'||ext==='gltf'?'m (glTF declared units)':'source units; uncalibrated'};this.warnings.push(...context.warnings());$('modelStats').textContent=meshes+' 个网格 · '+triangles.toLocaleString('zh-CN')+' 三角面\n原尺寸 '+[size.x,size.y,size.z].map(x=>Number(x.toPrecision(5))).join(' × ')+(ext==='glb'||ext==='gltf'?' 米':' 原文件单位，待校准');this.setMode($('refRenderMode').value);this.resize();this.fit();}catch(error){if(object&&(!this.root||this.root.children[0]!==object))disposeObject(object);throw error;}finally{context.dispose();}}
}
function restoreModelStage(){const stage=$('modelStage'),dock=$('modelDock');if(stage&&dock&&stage.parentElement!==dock){dock.append(stage);refViewer?.resize();}}
function expandModel(){if(activeRef()?.kind!=='model')return;$('modelModalTitle').textContent=activeRef().title;$('modelModalBody').append($('modelStage'));openModal('modelModal');requestAnimationFrame(()=>{refViewer?.resize();refViewer?.fit();});}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function addZipBlob(zip,path,blob){const entry=new R.archive.ZipPassThrough(path);zip.add(entry);const reader=blob.stream().getReader();for(;;){const {value,done}=await reader.read();if(done){entry.push(new Uint8Array(),true);break;}entry.push(value);}}
async function exportProject(){if(ingestBusy){toast('请先让当前文件接收完成。');return;}try{$('exportBtn').disabled=true;$('exportBtn').textContent='正在保存原文件';await flushRefNotes();await Promise.all([...pendingRefWrites]);const manifest={schema:'tiles-mother-collaboration',version:VERSION,exportedAt:new Date().toISOString(),project:clone(project),referenceFiles:refs.map(r=>({...refMetadata(r),archivePath:'files/'+r.id+'/'+r.filename})),qa:lastQA,sourcePackage:SOURCE,visualApproved:false,productionApproved:false,privacy:'Original reference bytes, no automatic network upload.'};const chunks=[];let resolve,reject;const done=new Promise((r,j)=>{resolve=r;reject=j;}),zip=new R.archive.Zip((error,data,final)=>{if(error){reject(error);return;}chunks.push(data);if(final)resolve(new Blob(chunks,{type:'application/zip'}));});await addZipBlob(zip,'workspace.json',new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'}));for(const r of refs){$('exportBtn').textContent='保存 '+r.filename.slice(0,18);await addZipBlob(zip,'files/'+r.id+'/'+r.filename,r.blob);}zip.end();download(await done,'Tiles_Mother_V02_Work_Record_'+new Date().toISOString().slice(0,10)+'.zip');toast('协作包已保存。包含完整原文件、笔记、参数和种子。');}catch(error){toast('保存失败：'+error.message);}finally{$('exportBtn').disabled=false;$('exportBtn').textContent='保存协作包';}}
function decodeDataURL(s){if(typeof s!=='string'||!/^data:[^,]*;base64,/.test(s))throw Error('旧记录的文件编码无效。');const i=s.indexOf(','),type=s.slice(5,s.indexOf(';')),raw=atob(s.slice(i+1));if(raw.length>REF_LIMIT)throw Error('原文件过大。');return new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type});}
async function importProject(file){try{await ingestTail;let data,archive;if(extOf(file.name)==='zip'){archive=await unpackZip(file);if(!archive['workspace.json'])throw Error('这份 ZIP 没有协作记录。模型资料包可直接拖到参考区。');data=JSON.parse(new TextDecoder().decode(archive['workspace.json']));}else{if(file.size>230*1024*1024)throw Error('旧版 JSON 记录过大。');data=JSON.parse(await file.text());}if(data.schema!=='tiles-mother-collaboration')throw Error('无法识别 Tiles Mother 协作记录。');const next=validateProject(data.project),list=data.referenceFiles||data.referenceImages;if(!Array.isArray(list)||list.length>MAX_REFS)throw Error('记录中的文件数量无效。');let total=0;const imported=[];for(const r of list){const path=safePath(r.relativePath||r.filename||'reference'),filename=path.split('/').pop();let blob;if(archive){const name=safePath(r.archivePath);if(!archive[name])throw Error('协作包缺少原文件：'+filename);blob=new Blob([archive[name]],{type:r.mime||MIME[extOf(filename)]||'application/octet-stream'});}else blob=decodeDataURL(r.dataURL);total+=blob.size;if(blob.size>REF_LIMIT||total>TOTAL_LIMIT)throw Error('协作包超出安全大小范围。');const hash=await sha256(blob);if(r.sha256&&hash!==r.sha256)throw Error('原文件 SHA256 不匹配：'+filename);const record={...r,id:makeId(),title:String(r.title||filename).slice(0,160),filename,relativePath:path,bundleId:String(r.bundleId||'import-'+makeId()),mime:blob.type,size:blob.size,blob,sha256:hash,kind:kindOf(filename,blob.type),type:Object.hasOwn(PROFILE_DEFS,r.type)?r.type:'unknown',source:String(r.source||'').slice(0,500),notes:String(r.notes||'').slice(0,6000),status:'pending',createdAt:r.createdAt||new Date().toISOString()};delete record.dataURL;delete record.archivePath;if(record.kind==='image')try{Object.assign(record,await imageMeta(blob));}catch{}imported.push(record);}
 const unique=imported.filter(r=>!refs.some(x=>x.sha256===r.sha256&&x.relativePath===r.relativePath));if(refs.length+unique.length>MAX_REFS||refs.reduce((n,r)=>n+r.size,0)+unique.reduce((n,r)=>n+r.size,0)>TOTAL_LIMIT)throw Error('合并后资料超过安全上限。');if(!confirm('载入记录会更新母体参数，并合并 '+unique.length+' 份原文件。继续吗？'))return;await flushRefNotes();project=next;for(const r of unique){await saveRefRecord(r);r.url=URL.createObjectURL(r.blob);refs.push(r);}selectedRef=(unique.find(r=>r.kind==='model')||unique.at(-1))?.id||selectedRef;syncUI();rebuild(true);renderRefs(true);saveSoon();toast('协作记录已载入，原文件校验完成。人工批准继续保持 false。');}catch(error){toast('记录未能载入：'+error.message);}finally{$('projectFile').value='';}}
function wireReferences(){
 $('dropzone').onclick=()=>$('refFiles').click();$('dropzone').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('refFiles').click();}};$('chooseFiles').onclick=()=>$('refFiles').click();$('chooseFolder').onclick=()=>$('refFolders').click();$('refFiles').onchange=e=>addFiles(e.target.files);$('refFolders').onchange=e=>addFiles(e.target.files);document.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();e.dataTransfer.dropEffect='copy';}});document.addEventListener('drop',async e=>{if(![...e.dataTransfer.types].includes('Files'))return;e.preventDefault();$('dropzone').classList.remove('drag');try{const entries=await droppedEntries(e.dataTransfer);await addFiles(entries);}catch(error){toast(error.message);}});$('dropzone').addEventListener('dragenter',()=>$('dropzone').classList.add('drag'));$('dropzone').addEventListener('dragleave',()=>$('dropzone').classList.remove('drag'));document.addEventListener('paste',e=>{const files=[...(e.clipboardData?.items||[])].filter(x=>x.kind==='file').map(x=>x.getAsFile()).filter(Boolean);if(files.length){e.preventDefault();addFiles(files);}});
 for(const id of ['refTitle','refType','refSource','refNotes'])$(id).addEventListener('input',editRef);
 $('deleteRef').onclick=async()=>{const r=activeRef();if(!r||!confirm('从当前浏览器移除“'+r.title+'”及对应笔记？原始文件和已导出的协作包不受影响。'))return;await flushRefNotes();await Promise.all([...pendingRefWrites]);if(db)try{await requestDB('refs','readwrite',s=>s.delete(r.id));}catch(error){toast('本地删除失败，资料继续保留。');return;}previewSerial++;if(activeModal==='modelModal')closeModal('modelModal');URL.revokeObjectURL(r.url);refs=refs.filter(x=>x.id!==r.id);selectedRef=refs[0]?.id;renderRefs(true);storageStatus();};
 $('downloadRef').onclick=()=>{const r=activeRef();if(r)download(r.blob,r.filename);};$('retryPreview').onclick=()=>{const r=activeRef();if(r)showReference(r);};$('enlargeRef').onclick=()=>{const r=activeRef();if(!r)return;$('lightboxImg').src=r.url;$('lightboxImg').alt=r.title;$('lightboxTitle').textContent=r.title+' · '+r.width+' × '+r.height+' px';$('lightboxStage').classList.remove('original');$('originalRef').textContent='原始像素';openModal('refModal');};$('originalRef').onclick=()=>{const is=$('lightboxStage').classList.toggle('original');$('originalRef').textContent=is?'适合窗口':'原始像素';};$('expandModel').onclick=expandModel;$('modelFit').onclick=()=>refViewer?.fit();$('refRenderMode').onchange=e=>refViewer?.setMode(e.target.value);$('modelCapture').onclick=()=>{refViewer?.draw();$('referenceCanvas').toBlob(b=>{if(b)download(b,'Tiles_Reference_'+(activeRef()?.filename||'model')+'.png');},'image/png');};$('jumpRefs').onclick=()=>{document.querySelector('.reference-rail').scrollIntoView({behavior:'smooth',block:'start'});$('dropzone').focus({preventScroll:true});};$('exportBtn').onclick=exportProject;$('importBtn').onclick=()=>$('projectFile').click();$('projectFile').onchange=e=>{if(e.target.files[0])importProject(e.target.files[0]);};
 window.addEventListener('beforeunload',e=>{if(refs.some(r=>!r.persisted)||ingestBusy){e.preventDefault();e.returnValue='';}});
}
function attachReferenceAPI(){window.TilesMother.references={addFiles,whenIdle:()=>ingestTail,getPreviewState:()=>clone(previewState),getCamera:()=>refViewer?{position:refViewer.camera.position.toArray(),target:refViewer.controls.target.toArray(),distance:refViewer.camera.position.distanceTo(refViewer.controls.target)}:null,select:id=>{if(!refs.some(r=>r.id===id))throw Error('Unknown reference');flushRefNotes();selectedRef=id;renderRefs(true);},fit:()=>refViewer?.fit(),expand:expandModel,sha256,streamHash:async blob=>{const h=new RefSHA256();h.update(new Uint8Array(await blob.arrayBuffer()));return h.hex();}};storageStatus();}
