/* New application. Does not load or patch any older Tiles Mother application. */
const UI={};document.querySelectorAll('[id]').forEach(e=>UI[e.id]=e);
const C=FieldCore,G=FieldGeometry;
const config={version:'field-core-r1-macroscopic',scene:'tiles',year:5,care:'abandoned',seed:314159,detail:1,micro:.75,warm:.8,wet:.65,moss:.75,separation:.025,diagnostic:0};
let framePending=0,frames=0,buildNumber=0,buildMs=0,renderSubmitMs=0,playing=false,playTimer=0,lastSnap=null,seat=null;
const materials=[FieldMaterial.create(0),FieldMaterial.create(1),FieldMaterial.create(2)];
const renderer=new THREE.WebGLRenderer({canvas:UI.stage,antialias:true,alpha:true,powerPreference:'default',preserveDrawingBuffer:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));
renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;
const world=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.005,120);world.add(new THREE.HemisphereLight(0xffffff,0x7a7267,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(-1,3,2);world.add(light);
let root=new THREE.Group();world.add(root);const cache=new Map(),meshes=[];const cameraState={theta:.48,phi:.67,distance:1.32,target:new THREE.Vector3(0,.012,0)};
function cached(key,create){if(!cache.has(key)){cache.set(key,create());if(cache.size>32){const k=cache.keys().next().value;cache.get(k).dispose();cache.delete(k);}}return cache.get(key);}
const tileBase=kind=>cached('tile-'+kind,()=>G.tile(kind,11));
function makeInstances(geometry,material,data,parent=root){if(!data.length)return null;const geom=geometry.clone(),pa=new Float32Array(data.length*4),sc=new Float32Array(data.length*3);data.forEach((v,i)=>{pa.set(v.params,i*4);let ms=material===materials[1]?new THREE.Vector3().setFromMatrixScale(v.matrix):new THREE.Vector3(1,1,1);sc.set(ms.toArray(),i*3);});geom.setAttribute('matterScale',new THREE.InstancedBufferAttribute(sc,3));geom.setAttribute('params',new THREE.InstancedBufferAttribute(pa,4));const mesh=new THREE.InstancedMesh(geom,material,data.length);mesh.instanceMatrix.setUsage(THREE.StaticDrawUsage);data.forEach((v,i)=>mesh.setMatrixAt(i,v.matrix));mesh.instanceMatrix.needsUpdate=true;mesh.frustumCulled=false;parent.add(mesh);meshes.push(mesh);return mesh;}
function matrix(x,y,z,rx=0,ry=0,rz=0,sx=1,sy=1,sz=1){return new THREE.Matrix4().compose(new THREE.Vector3(x,y,z),new THREE.Quaternion().setFromEuler(new THREE.Euler(rx,ry,rz)),new THREE.Vector3(sx,sy,sz));}
function params(seed,interiorAge=0){return [seed,Math.min(1,.25+config.year/15),config.care==='abandoned'?config.wet*.7:config.wet*.15,C.h(seed,71)];}
function resetRoot(){for(const m of meshes){m.geometry.dispose();if(!materials.includes(m.material))m.material.dispose();}meshes.length=0;world.remove(root);root=new THREE.Group();world.add(root);}
function addMoss(kind,pose,seed,amount=1,piece=0,path=null,target=[]){if(config.moss<=.01)return;const effectiveYears=config.care==='abandoned'?config.year:0;const n=Math.floor((5+effectiveYears*1.05)*config.moss*amount);for(let i=0;i<n;i++){const s=(C.h(seed,i,51)-.5)*1.2,t=.18+C.h(seed,i,61)*.60;if(path&&piece<0&&t>path.at(s)-.1)continue;if(path&&piece>0&&t<path.at(s)+.1)continue;
 const p=C.surface(kind,s,t,11),normal=C.macroNormal(kind,s,t),orient=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(...normal)),a=(.006+C.h(seed,i,78)*.017)*(kind==='cover'?.68:1),height=(.002+.006*C.h(seed,i,83))*(.5+config.year/9)*Math.sqrt(config.moss);
 orient.multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),C.h(seed,i,17)*6.283185));const mm=new THREE.Matrix4().compose(new THREE.Vector3(...p).addScaledVector(new THREE.Vector3(...normal),-.0007),orient,new THREE.Vector3(a,height,a*(.55+.6*C.h(seed,i,81))));mm.premultiply(pose);target.push({matrix:mm,params:params(seed+i*217)});}
 return target;}
function shadowFloor(y,x=0,z=0,size=2){const geo=new THREE.PlaneGeometry(size,size);geo.rotateX(-Math.PI/2);geo.deleteAttribute('uv');const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{},vertexShader:'varying vec3 p;void main(){p=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(p,1.);}',fragmentShader:'varying vec3 p;void main(){float d=length(p.xz*vec2(1.15,1.8));float a=.14*exp(-d*d*15.);gl_FragColor=vec4(.12,.11,.09,a);}'});const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);root.add(m);meshes.push(m);}
function gallery(){const moss=[];const year=config.care==='abandoned'?config.year:0,fracture=year>=3,separation=config.separation*C.smooth(2,7,year);
 const specs=[{kind:'pan',x:-.31,seed:1121,split:false},{kind:'pan',x:0,seed:4811,split:fracture},{kind:'cover',x:.30,seed:3251,split:false}];
 for(const spec of specs){spec.seed=((spec.seed^config.seed)>>>0)%65000;let cut=C.crackPath(spec.seed,config.wet);for(const piece of spec.split?[-1,1]:[0]){const geo=piece?cached(`${spec.kind}-${spec.seed}-${config.wet}-${piece}`,()=>G.tile(spec.kind,11,piece,cut)):tileBase(spec.kind),pose=matrix(spec.x,0,piece*separation,0,0,piece?piece*.025:0);makeInstances(geo,materials[0],[{matrix:pose,params:params(spec.seed)}]);addMoss(spec.kind,pose,spec.seed,1,piece,cut,moss);}}
 makeInstances(cached('moss',()=>G.moss(11)),materials[2],moss);shadowFloor(-.080);lastSnap={counts:{total:3,live:3},note:'独立材料样片，中央断口为可展开的检查件'};
}
function woodLab(){const moss=[],seed=((1267^config.seed)>>>0)%65000,split=config.care==='abandoned'&&config.year>=3,sep=split?config.separation*1.8:0;
 for(const piece of split?[-1,1]:[0]){const geo=cached('wood-'+piece,()=>G.wood(5,piece)),pose=matrix(.04+piece*sep,.015,0,0,Math.PI/2,0);makeInstances(geo,materials[1],[{matrix:pose,params:params(seed)}]);}
 const pose=matrix(-.08,-.092,.22,0,.2,0);makeInstances(tileBase('pan'),materials[0],[{matrix:pose,params:params(771)}]);addMoss('pan',pose,771,.7,0,null,moss);makeInstances(cached('moss',()=>G.moss(11)),materials[2],moss);shadowFloor(-.15);lastSnap={counts:{total:split?3:2,live:split?3:2},note:'木材剖裂检查件；展开位置用于观察，无刚体碰撞求解'};
}
function roof(rows,cols){if(!seat)seat=G.seats(tileBase('pan'),tileBase('cover'));const snap=C.snapshot(rows,cols,config.seed,config.year,config.care,config.wet);if(rows===6&&cols===5){snap.pan=snap.pan.filter(e=>!(e.r>=3&&e.c===4));snap.cover=snap.cover.filter(e=>!(e.r>=3&&e.c===3));snap.counts.total=48;snap.counts.live=snap.pan.filter(e=>!e.missing).length+snap.cover.filter(e=>!e.missing).length;snap.counts.panLost=snap.pan.filter(e=>e.missing).length;snap.counts.coverLost=snap.cover.filter(e=>e.missing).length;snap.footprint='48-tile cropped assembly: 27 pan, 21 covers, three outermost bays excluded from section';}lastSnap=snap;const step=.198,spacing=seat.spacing,pans=[],covers=[],wood=[],moss=[],slope=.32,group=new THREE.Group();group.rotation.x=-slope;root.add(group);const W=cols*spacing,L=(rows-1)*step+.238;
 for(const e of snap.pan){if(e.missing)continue;const x=(e.c-(cols-1)/2)*spacing,z=(e.r-(rows-1)/2)*step,pose=matrix(x,seat.pan.raise,z,seat.pan.pitch);pans.push({matrix:pose,params:params(e.seed)});if(moss.length<(rows>10?192:40)&&C.h(config.seed,e.r,e.c)<config.moss*.22)addMoss('pan',pose,e.seed,.30,0,null,moss);}
 for(const e of snap.cover){if(e.missing)continue;const x=(e.c-(cols-2)/2)*spacing,z=(e.r-(rows-1)/2)*step,pose=matrix(x,seat.cover.raise,z+seat.cover.offsetZ,seat.cover.pitch);covers.push({matrix:pose,params:params(e.seed)});}
 makeInstances(tileBase('pan'),materials[0],pans,group);makeInstances(tileBase('cover'),materials[0],covers,group);
 // Contiguous live timber runs are grouped; gaps are actual missing spans.
 const woodGeo=cached('wood-bearing',()=>G.bearingWood());
 for(let c=0;c<=cols;c++){let start=-1;for(let r=0;r<=rows;r++){let live=r<rows&&!snap.rafters[r*(cols+1)+c].failed;if(live&&start<0)start=r;if(!live&&start>=0){let end=r-1,len=(end-start+1)*step+.04,z=((start+end)/2-(rows-1)/2)*step;wood.push({matrix:matrix((c-cols/2)*spacing,-seat.rafterRadius,z,0,0,0,seat.rafterRadius/.057,seat.rafterRadius/.057,len/.63),params:params(c*151+8)});start=-1;}}}
 for(let b=0;b<4;b++){let start=-1;for(let c=0;c<=cols;c++){const live=c<cols&&!snap.beams[b*cols+c].failed;if(live&&start<0)start=c;if(!live&&start>=0){let end=c-1,len=(end-start+1)*spacing,x=((start+end)/2-(cols-1)/2)*spacing,z=(b/3-.5)*(rows-1)*step;wood.push({matrix:matrix(x,-seat.rafterRadius*2-.052,z,0,Math.PI/2,0,.052/.057,.052/.057,len/.63),params:params(1350+b*71)});start=-1;}}}
 makeInstances(woodGeo,materials[1],wood,group);makeInstances(cached('moss',()=>G.moss(11)),materials[2],moss.slice(0,rows>10?192:40),group);shadowFloor(-1,0,0,15);
}
const titles={tiles:['陶瓦 · 物质与断面','独立参考坐标 / 多尺度材料 / 自然边界'],wood:['木材 · 纤维与剖裂','轴向纤维 / 风化沟槽 / 非平面断口'],assembly:['48片截取 · 支承关系','真实瓦壳 / 共享圆椽 / 四道横梁'],roof:['860片 · 整坡屋面','440片板瓦 + 420片筒瓦 / 按需显示']};
function build(keepCamera=false){const t=performance.now();buildNumber++;resetRoot();if(config.scene==='tiles')gallery();else if(config.scene==='wood')woodLab();else if(config.scene==='assembly')roof(6,5);else roof(20,22);buildMs=performance.now()-t;syncUniforms();if(!keepCamera)fit('iso');UI.sceneTitle.textContent=titles[config.scene][0];UI.sceneSub.textContent=titles[config.scene][1];UI.live.textContent=lastSnap.counts.live;UI.count.textContent=lastSnap.counts.total;UI.cpu.textContent=buildMs.toFixed(0)+' ms';UI.phase.textContent=config.care==='maintained'?'持续修缮对照':config.year<3?'早期失养':config.year<6?'局部漏损':config.year<9?'成片失养':'严重失养';UI.woodState.textContent=lastSnap.counts.beamFailed!==undefined?`梁段失效 ${lastSnap.counts.beamFailed} · 椽段失效 ${lastSnap.counts.rafterFailed}${config.scene==='assembly'?' · 本截取27板瓦 / 21筒瓦':''}`:lastSnap.note;document.body.dataset.ready='true';invalidate();}
function syncUniforms(){for(const m of materials){m.uniforms.uDetail.value=config.detail;m.uniforms.uMicro.value=config.micro;m.uniforms.uWarm.value=config.warm;m.uniforms.uWet.value=config.wet;m.uniforms.uDiagnostic.value=config.diagnostic;}}
function setCamera(){const s=cameraState,r=s.distance;camera.position.set(s.target.x+r*Math.sin(s.theta)*Math.cos(s.phi),s.target.y+r*Math.sin(s.phi),s.target.z+r*Math.cos(s.theta)*Math.cos(s.phi));camera.lookAt(s.target);camera.updateMatrixWorld();}
function fit(view){let dist=config.scene==='roof'?8.1:config.scene==='assembly'?2.30:config.scene==='wood'?1.18:1.37;cameraState.distance=(view==='close'?.64:dist)*Math.max(1,1.05/camera.aspect);cameraState.target.set(0,config.scene==='wood'?-.005:0,0);cameraState.theta=view==='end'?0:.42;cameraState.phi=view==='top'?1.53:view==='under'?-.72:view==='end'?.05:.68;if(config.scene==='roof'||config.scene==='assembly'){cameraState.phi=view==='under'?-.84:view==='top'?1.53:view==='end'?.05:.67;cameraState.theta=.36;}setCamera();invalidate();}
function render(){framePending=0;setCamera();let t=performance.now();renderer.render(world,camera);renderSubmitMs=performance.now()-t;frames++;UI.draws.textContent=renderer.info.render.calls;UI.tris.textContent=(renderer.info.render.triangles/1000).toFixed(1)+'k';UI.renderTime.textContent=renderSubmitMs.toFixed(1)+' ms';}
function invalidate(){if(!framePending)framePending=requestAnimationFrame(render);}
function resize(){const r=UI.stage.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);const priorAspect=camera.aspect;camera.aspect=r.width/r.height;cameraState.distance*=Math.max(1,1.05/camera.aspect)/Math.max(1,1.05/priorAspect);camera.updateProjectionMatrix();invalidate();}new ResizeObserver(resize).observe(UI.viewport);
function refreshUI(){UI.years.value=config.year;for(const k of ['detail','micro','warm','wet','moss','separation']){UI[k].value=config[k];UI[k+'Value'].textContent=k==='separation'?Math.round(config[k]*1000)+' mm':config[k].toFixed(2);}UI.yearLabel.textContent=config.year.toFixed(config.year%1?1:0);document.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('active',b.dataset.scene===config.scene));document.querySelectorAll('[data-care]').forEach(b=>b.classList.toggle('active',b.dataset.care===config.care));document.querySelectorAll('[data-year]').forEach(b=>b.classList.toggle('active',+b.dataset.year===config.year));}
function change(values,keep=false){for(const [k,v] of Object.entries(values)){if(!Object.hasOwn(config,k))throw Error('Unknown parameter '+k);if(typeof config[k]==='number'&&!Number.isFinite(v))throw Error('Finite number required: '+k);}if(values.year!==undefined&&(values.year<0||values.year>15))throw Error('Year outside 0..15');if(values.scene!==undefined&&!Object.hasOwn(titles,values.scene))throw Error('Unknown scene');Object.assign(config,values);refreshUI();const materialOnly=Object.keys(values).every(k=>['detail','micro','warm','diagnostic'].includes(k));if(materialOnly){syncUniforms();invalidate();}else build(keep);}
for(const b of document.querySelectorAll('[data-scene]'))b.onclick=()=>change({scene:b.dataset.scene});for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>fit(b.dataset.view);for(const b of document.querySelectorAll('[data-year]'))b.onclick=()=>change({year:+b.dataset.year},true);for(const b of document.querySelectorAll('[data-care]'))b.onclick=()=>change({care:b.dataset.care},true);
UI.years.oninput=()=>{UI.yearLabel.textContent=(+UI.years.value).toFixed(1);};UI.years.onchange=()=>change({year:+UI.years.value},true);
for(const name of ['detail','micro','warm','wet']){UI[name].oninput=()=>{config[name]=+UI[name].value;UI[name+'Value'].textContent=(+UI[name].value).toFixed(2);syncUniforms();invalidate();};}UI.wet.onchange=()=>build(true);
UI.moss.oninput=()=>UI.mossValue.textContent=(+UI.moss.value).toFixed(2);UI.moss.onchange=()=>{config.moss=+UI.moss.value;build(true);};UI.separation.oninput=()=>UI.separationValue.textContent=Math.round(+UI.separation.value*1000)+' mm';UI.separation.onchange=()=>{config.separation=+UI.separation.value;build(true);};
UI.microToggle.onclick=()=>{config.micro=config.micro>.01?0:.75;UI.micro.value=config.micro;UI.microValue.textContent=config.micro.toFixed(2);syncUniforms();invalidate();};
UI.diagnostic.onchange=()=>{config.diagnostic=+UI.diagnostic.value;syncUniforms();invalidate();};UI.newSeed.onclick=()=>change({seed:Math.floor(C.h(config.seed,13)*65000)},true);
UI.export.onclick=()=>{let blob=new Blob([JSON.stringify({recipe:config,source:'Tiles Mother Field Core R1',unit:'m',timeUnit:'year',calibrated:false},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Tiles_Mother_Field_Recipe.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);};
UI.panelToggle.onclick=()=>{document.body.classList.toggle('settings-open');setTimeout(resize,100);};
UI.play.onclick=()=>{playing=!playing;UI.play.textContent=playing?'暂停':'播放';if(!playing){clearTimeout(playTimer);return;}const tick=()=>{if(!playing)return;change({year:Math.min(15,config.year+.5)},true);if(config.year>=15){playing=false;UI.play.textContent='播放';}else playTimer=setTimeout(tick,700);};tick();};
const points=new Map();let gesture=null;UI.stage.addEventListener('contextmenu',e=>e.preventDefault());UI.stage.addEventListener('pointerdown',e=>{UI.stage.setPointerCapture(e.pointerId);points.set(e.pointerId,[e.clientX,e.clientY]);gesture=null;});UI.stage.addEventListener('pointermove',e=>{if(!points.has(e.pointerId))return;const old=points.get(e.pointerId);points.set(e.pointerId,[e.clientX,e.clientY]);if(points.size===2){const p=[...points.values()],dist=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]);if(gesture)cameraState.distance=C.clamp(cameraState.distance*gesture/dist,.20,30);gesture=dist;}else{let dx=e.clientX-old[0],dy=e.clientY-old[1];if(e.buttons===2||e.shiftKey){const scale=cameraState.distance*.0012;cameraState.target.x-=dx*scale;cameraState.target.y+=dy*scale;}else{cameraState.theta-=dx*.006;cameraState.phi=C.clamp(cameraState.phi+dy*.006,-1.5,1.54);}}invalidate();});for(let type of ['pointerup','pointercancel'])UI.stage.addEventListener(type,e=>{points.delete(e.pointerId);gesture=null;});UI.stage.addEventListener('wheel',e=>{e.preventDefault();cameraState.distance=C.clamp(cameraState.distance*Math.exp(e.deltaY*.001),.17,40);invalidate();},{passive:false});UI.stage.ondblclick=()=>fit('iso');
window.TilesField={version:config.version,get config(){return {...config};},set:change,fit,render,stats:()=>({buildNumber,buildMs,renderSubmitMs,frames,framePending,draws:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,counts:lastSnap?.counts,seat:seat?{pan:{raise:seat.pan.raise,pitch:seat.pan.pitch,gap:seat.pan.overlapGap},cover:{raise:seat.cover.raise,pitch:seat.cover.pitch,gap:seat.cover.overlapGap}}:null}),integrity:()=>({uvChannels:meshes.filter(m=>m.geometry.attributes.uv).length,materialMaps:materials.filter(m=>m.map||m.normalMap).length,oldAppLoaded:false}),orbit:(dx,dy=0)=>{cameraState.theta+=dx;cameraState.phi=C.clamp(cameraState.phi+dy,-1.5,1.54);invalidate();},snapshot:C.snapshot,shaderSources:()=>materials.map(m=>({vertex:m.vertexShader,fragment:m.fragmentShader})),scene:world,camera,renderer};
refreshUI();build();resize();
