const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const root=path.resolve(__dirname,'..'),THREE=require(root+'/reference/three_runtime.cjs'),c={THREE};vm.createContext(c);vm.runInContext(fs.readFileSync(root+'/source/core.js','utf8')+'\n'+fs.readFileSync(root+'/source/geometry.js','utf8')+'\nthis.G=FieldGeometry;',c);const G=c.G,p=G.tile('pan',11),cv=G.tile('cover',11),seat=G.seats(p,cv);
function mesh(g,pose){const P=g.attributes.position.array,I=g.index.array,m=new THREE.Matrix4().makeRotationX(pose.rx||0);m.setPosition(pose.x||0,pose.y||0,pose.z||0);const V=[];for(let i=0;i<P.length;i+=3){const v=new THREE.Vector3().fromArray(P,i).applyMatrix4(m);V.push([v.x,v.y,v.z]);}const out={top:[],bottom:[]};for(let i=0;i<I.length;i+=3){let t=[V[I[i]],V[I[i+1]],V[I[i+2]]],a=t[0],b=t[1],d=t[2],den=(b[0]-a[0])*(d[2]-a[2])-(b[2]-a[2])*(d[0]-a[0]);if(Math.abs(den)<1e-13)continue;let tri={t,den,minx:Math.min(...t.map(x=>x[0])),maxx:Math.max(...t.map(x=>x[0])),minz:Math.min(...t.map(x=>x[2])),maxz:Math.max(...t.map(x=>x[2]))};out[den<0?'top':'bottom'].push(tri);}return out;}
function height(T,p){let [a,b,c]=T.t,d=T.den,u=((p[0]-a[0])*(c[2]-a[2])-(p[1]-a[2])*(c[0]-a[0]))/d,v=((b[0]-a[0])*(p[1]-a[2])-(b[2]-a[2])*(p[0]-a[0]))/d;return a[1]+u*(b[1]-a[1])+v*(c[1]-a[1]);}
function clip(t1,t2){let poly=t1.map(p=>[p[0],p[2]]),dir=Math.sign((t2[1][0]-t2[0][0])*(t2[2][2]-t2[0][2])-(t2[1][2]-t2[0][2])*(t2[2][0]-t2[0][0]));for(let i=0;i<3;i++){let a=t2[i],b=t2[(i+1)%3],side=p=>dir*((b[0]-a[0])*(p[1]-a[2])-(b[2]-a[2])*(p[0]-a[0])),output=[];for(let j=0;j<poly.length;j++){let A=poly[j],B=poly[(j+1)%poly.length],da=side(A),db=side(B),ina=da>=-1e-12,inb=db>=-1e-12;if(ina)output.push(A);if(ina!==inb){let s=da/(da-db);output.push([A[0]+s*(B[0]-A[0]),A[1]+s*(B[1]-A[1])]);}}poly=output;if(!poly.length)break;}return poly;}
function pair(name,lower,upper){let min=Infinity,n=0,tests=0;for(const a of lower.top)for(const b of upper.bottom){if(a.maxx<b.minx||b.maxx<a.minx||a.maxz<b.minz||b.maxz<a.minz)continue;tests++;const pts=clip(a.t,b.t);for(const v of pts){n++;min=Math.min(min,height(b,v)-height(a,v));}}return {name,overlapVertices:n,trianglePairs:tests,minimumVerticalGapMm:Number.isFinite(min)?min*1000:null,pass:n>0&&min>=-.05/1000};}
const P=(x=0,z=0)=>mesh(p,{x,z,y:seat.pan.raise,rx:seat.pan.pitch}),C=(x=0,z=0)=>mesh(cv,{x,z:z+seat.cover.offsetZ,y:seat.cover.raise,rx:seat.cover.pitch}),results=[];
results.push(pair('pan longitudinal lap',P(),P(0,.198)));results.push(pair('cover longitudinal lap',C(),C(0,.198)));
for(const x of [-seat.spacing/2,seat.spacing/2])for(const z of [-.198,0,.198]){const a=pair('pan-cover '+x+' '+z,P(x,z),C());if(a.overlapVertices)results.push(a);}
const timber=G.bearingWood();timber.scale(seat.rafterRadius/.057,seat.rafterRadius/.057,1);for(const x of [-seat.spacing/2,seat.spacing/2])results.push(pair('pan on circular rafter '+x,mesh(timber,{x,y:-seat.rafterRadius}),P()));
const bilateral=results.filter(x=>x.name.startsWith('pan-cover')&&x.name.endsWith(' 0'));const bilateralPassed=bilateral.length===2&&bilateral.every(x=>x.minimumVerticalGapMm>=0&&x.minimumVerticalGapMm<=.5);
const out={bilateralPassed,method:'Independent projected triangle intersection, affine y evaluated at all intersection vertices; translational template configurations only',scope:'Common roof-slope rotation preserves intersections. This does not validate moss, arbitrary debris motion, or all material histories.',results,passed:results.every(x=>x.pass)&&bilateralPassed};fs.writeFileSync(root+'/qa/CONTACT.json',JSON.stringify(out,null,2));console.log(out);if(!out.passed)process.exitCode=1;
